// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// bt656_out //
// --------- //

#define bt656_out_wrap_target 0
#define bt656_out_wrap 1
#define bt656_out_pio_version 0

static const uint16_t bt656_out_program_instructions[] = {
            //     .wrap_target
    0x6008, //  0: out    pins, 8         side 0
    0xb042, //  1: nop                    side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program bt656_out_program = {
    .instructions = bt656_out_program_instructions,
    .length = 2,
    .origin = -1,
    .pio_version = bt656_out_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config bt656_out_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + bt656_out_wrap_target, offset + bt656_out_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

// ------------- //
// bt656_out_rev //
// ------------- //

#define bt656_out_rev_wrap_target 0
#define bt656_out_rev_wrap 8
#define bt656_out_rev_pio_version 0

#define bt656_out_rev_offset_entry 7u

static const uint16_t bt656_out_rev_program_instructions[] = {
            //     .wrap_target
    0x6108, //  0: out    pins, 8         side 0 [1]
    0xb142, //  1: nop                    side 1 [1]
    0x6108, //  2: out    pins, 8         side 0 [1]
    0xb142, //  3: nop                    side 1 [1]
    0x6108, //  4: out    pins, 8         side 0 [1]
    0xb142, //  5: nop                    side 1 [1]
    0x6108, //  6: out    pins, 8         side 0 [1]
    0x90a0, //  7: pull   block           side 1
    0xb0f7, //  8: mov    osr, ::osr      side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program bt656_out_rev_program = {
    .instructions = bt656_out_rev_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = bt656_out_rev_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config bt656_out_rev_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + bt656_out_rev_wrap_target, offset + bt656_out_rev_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

