// Every text the firmware sends out or shows: Serial/report() protocol
// lines, the on-device menu and badge labels, the splash, and the
// card names. Not here: comments, static_assert() messages (compile
// time only) and the field-name keys the "name=value" parser matches
// against (PC Software/src/BoardConfig.cs), since those are read, not
// shown, and moving them would not remove the duplication between the
// two sides anyway.
#ifndef LANGUAGE_H
#define LANGUAGE_H

static const char LANG_08LX[] = " %08lX";
static const char LANG_0X17_AFTER_THE_SOFTWARE[] = "    0x17 after the software reset: 0x%02X\n";
static const char LANG_0X_02X_DID_NOT[] = "    0x%02X did not answer within %d ms, walking the whole bus...\n";
static const char LANG_0_WAITING_FOR_CORE1_TO[] = "\n[0] Waiting for core1 to start the pixel clock...";
static const char LANG_1_5_LUMA_FILTER[] = "   1 .. 5  luma filter";
static const char LANG_1_HARDWARE_RESET[] = "\n[1] Hardware reset...";
static const char LANG_2D_S_S_S[] = "      %2d %s %s%s%s%s\n";
static const char LANG_2_MEASURING_THE_I2C_LINES[] = "\n[2] Measuring the I2C lines...";
static const char LANG_3_I2C_BUS_SCAN[] = "\n[3] I2C bus scan...";
static const char LANG_4_CHECKING_THE_RESET_VALUE[] = "\n[4] Checking the reset value of the power register (0x00)...";
static const char LANG_5_READ_WRITE_TEST_ON[] = "\n[5] Read/write test on register 0xA0 (hue, which is off)...";
static const char LANG_6_TESTING_THE_SOFTWARE_RESET[] = "\n[6] Testing the software reset (0x17 bit 1, self clearing)...";
static const char LANG_7_SWITCHING_ON_DAC1_AND[] = "\n[7] Switching on DAC1 and the PLL only (0x00 = 0x10)...";
static const char LANG_8_PAL_AND_EXTERNAL_PIXEL[] = "\n[8] PAL and external pixel data (BT.656 embedded sync)...";
static const char LANG_ADV_CONFIGURATION_WRITTEN_AGAIN[] = "[adv] configuration written again";
static const char LANG_ADV_HARDWARE_RESET_AND_RECONFIGURATION[] = "[adv] hardware reset and reconfiguration";
static const char LANG_ADV_NOTE[] = "[adv] note: ";
static const char LANG_ADV_REGISTER_0X_02X_IS[] = "[adv] register 0x%02X is 0x%02X, we wrote 0x%02X, configuration written again (%lu deviations)\n";
static const char LANG_AP2_VARIANT[] = "AP2 variant";
static const char LANG_ASPECT[] = "[aspect] ";
static const char LANG_ASPECT_2[] = "Aspect";
static const char LANG_ASPECT_D_D_S[] = "[aspect] %d/%d %s\n";
static const char LANG_A_EVERY_SETTING_AS[] = "   A       every setting as text, for the PC tool";
static const char LANG_A_LU[] = "A%lu\n";
static const char LANG_A_PICK_AN_ANALOGUE[] = "   a       pick an analogue control; + and - turn it, 0 = neutral";
static const char LANG_BOARD_S[] = "Board: %s\n";
static const char LANG_BRING_UP_FINISHED[] = "\n=== Bring-up finished ===";
static const char LANG_B_G924_CHROMA_TEST[] = "   b       G924: chroma test bars on/off";
static const char LANG_CANCELLED[] = "cancelled";
static const char LANG_CARDDUMP[] = "carddump";
static const char LANG_CARDDUMP_ABORTED_AT_ROW_D[] = "\n[carddump] aborted at row %d: %s\n";
static const char LANG_CARDDUMP_BOXES_D_D_D[] = "[carddump] boxes %d %d %d %d %d %d mode %d\n";
static const char LANG_CARDDUMP_BOXES_NONE[] = "[carddump] boxes none";
static const char LANG_CARDDUMP_CARD_D_RLE_D[] = "[carddump] card %d, rle, %d x %d, crc 0x%08lX\n";
static const char LANG_CARDDUMP_DONE[] = "[carddump] done";
static const char LANG_CARDDUMP_FAILED_A_DUMP_IS[] = "[carddump] failed, a dump is already running";
static const char LANG_CARDDUMP_LINEBOX_D_D_D[] = "[carddump] linebox %d %d %d %d\n";
static const char LANG_CARDDUMP_LINEBOX_NONE[] = "[carddump] linebox none";
static const char LANG_CARDDUMP_READY_SEND_THE_CARD[] = "[carddump] ready, send the card number";
static const char LANG_CARD_D_D_S_LU[] = "[card] %d/%d %s -- %lu us, %lu rows late, %lu times out of data, %s\n";
static const char LANG_CARD_D_SHOWID_D_SHOWSUB[] = "[card] %d showid=%d showsub=%d ticker=%d tickery=%d tickerfont=%d tickerspeed=%d tickerscale=%d textfont=%d fixedfont=%d aspect=%d insert=%d moving=%d enabled=%d photo=%d own=%d hasid=%d hasbox=%d hasline=%d hassub=%d customphoto=%d option=%d tickercolor=%06lX idcolor=%06lX subcolor=%06lX inscolor=%06lX crc=%08lX ";
static const char LANG_CARD_ENABLED[] = "Card enabled";
static const char LANG_CFG[] = "[cfg] ";
static const char LANG_CFG_ASPECTS_D[] = "[cfg] aspects %d\n";
static const char LANG_CFG_BEGIN[] = "[cfg] begin";
static const char LANG_CFG_CARD[] = "[cfg] card ";
static const char LANG_CFG_CARDS_D[] = "[cfg] cards %d\n";
static const char LANG_CFG_CARD_D[] = "[cfg] card %d\n";
static const char LANG_CFG_CHROMA_D[] = "[cfg] chroma %d\n";
static const char LANG_CFG_CLOCK_04D_02D_02D[] = "[cfg] clock %04d-%02d-%02d %02d:%02d:%02d\n";
static const char LANG_CFG_CONTESTNR_D[] = "[cfg] contestnr %d\n";
static const char LANG_CFG_DATEFMT_D[] = "[cfg] datefmt %d\n";
static const char LANG_CFG_DIRTY_D[] = "[cfg] dirty %d\n";
static const char LANG_CFG_DISPLAYBRIGHT_D[] = "[cfg] displaybright %d\n";
static const char LANG_CFG_DSTAUTO_D[] = "[cfg] dstauto %d\n";
static const char LANG_CFG_END[] = "[cfg] end";
static const char LANG_CFG_FAILED_AN_EMPTY_SLOT[] = "[cfg] failed, an empty slot has nothing to show";
static const char LANG_CFG_FAILED_EXPECTED_NAME_VALUE[] = "[cfg] failed, expected name=value";
static const char LANG_CFG_FAILED_NO_SEQUENCE_AND[] = "[cfg] failed, no sequence and no filled photograph slots";
static const char LANG_CFG_FAILED_NO_SUCH_CARD[] = "[cfg] failed, no such card";
static const char LANG_CFG_FAILED_NO_SUCH_CARD_2[] = "[cfg] failed, no such card setting";
static const char LANG_CFG_FAILED_NO_SUCH_CONTROL[] = "[cfg] failed, no such control";
static const char LANG_CFG_FAILED_NO_SUCH_FONT[] = "[cfg] failed, no such font";
static const char LANG_CFG_FAILED_NO_SUCH_SETTING[] = "[cfg] failed, no such setting";
static const char LANG_CFG_FAILED_NO_SUCH_TELETEXT[] = "[cfg] failed, no such teletext row";
static const char LANG_CFG_FAILED_THE_NAME_IS[] = "[cfg] failed, the name is too long";
static const char LANG_CFG_FAILED_THIS_CARD_HAS[] = "[cfg] failed, this card has no place for the moving line";
static const char LANG_CFG_FAILED_TRANSPARENT_DOES_NOT[] = "[cfg] failed, transparent does not fit on a photograph";
static const char LANG_CFG_FONTS_D[] = "[cfg] fonts %d\n";
static const char LANG_CFG_G924BARS_D[] = "[cfg] g924bars %d\n";
static const char LANG_CFG_INSERTS_D[] = "[cfg] inserts %d\n";
static const char LANG_CFG_ITS_D[] = "[cfg] its %d\n";
static const char LANG_CFG_LUMA_D[] = "[cfg] luma %d\n";
static const char LANG_CFG_PROTO_D[] = "[cfg] proto %d\n";
static const char LANG_CFG_SET_CARDCRC_CRC_08LX[] = "[cfg] set cardcrc crc=%08lX\n";
static const char LANG_CFG_SET_CURRENTCARD_CARD_D[] = "[cfg] set currentcard card=%d\n";
static const char LANG_CFG_SET_S[] = "[cfg] set %s\n";
static const char LANG_CFG_SET_S_CRC_08LX[] = "[cfg] set %s crc=%08lX\n";
static const char LANG_CFG_SLIDEFADE_D[] = "[cfg] slidefade %d\n";
static const char LANG_CFG_SLIDESHOW_D[] = "[cfg] slideshow %d\n";
static const char LANG_CFG_SLOTS_D[] = "[cfg] slots %d\n";
static const char LANG_CFG_STARTCARD_D[] = "[cfg] startcard %d\n";
static const char LANG_CFG_TCGAP2_D[] = "[cfg] tcgap2 %d\n";
static const char LANG_CFG_TELETEXTROWS_D[] = "[cfg] teletextrows %d\n";
static const char LANG_CFG_TELETEXT_D[] = "[cfg] teletext %d\n";
static const char LANG_CFG_VBI_D[] = "[cfg] vbi %d\n";
static const char LANG_CHECK_SDA_SCL_THE[] = "    -> check SDA/SCL, the pull-ups (R2/R3) and the supply.";
static const char LANG_CHECK_THE_ALSB_STRAP[] = "    -> check the ALSB strap and the I2C wiring.";
static const char LANG_CHROMA[] = "[chroma] ";
static const char LANG_CHROMA_BARS[] = "Chroma bars";
static const char LANG_CHROMA_D_D_S[] = "[chroma] %d/%d %s\n";
static const char LANG_CLK[] = "CLK";
static const char LANG_CLOCK_04D_02D_02D_02D[] = "[clock] %04d-%02d-%02d %02d:%02d:%02d\n";
static const char LANG_CLOCK_INPUT_S_THE_KEYS[] = "[clock] input %s, the keys work again\n";
static const char LANG_CLOCK_SET_TO_04D_02D[] = "[clock] set to %04d-%02d-%02d %02d:%02d:%02d\n";
static const char LANG_CLOCK_SYSCLK_LU_03LU[] = "Clock: sysclk %lu.%03lu MHz / divisor %d / 2 = CLKIN %lu.%06lu MHz\n";
static const char LANG_CLOCK_USAGE_TYYYY_MM_DD[] = "[clock] usage: Tyyyy-mm-dd hh:mm:ss  or  Thh:mm:ss";
static const char LANG_CLOCK_FROM_RTC_04D[] = "[clock] RV-3028 RTC found, time kept: %04d-%02d-%02d %02d:%02d:%02d (status 0x%02X, backup 0x%02X)\n";
static const char LANG_CLOCK_RTC_TIME_LOST[] = "[clock] RV-3028 found but its time was lost (status 0x%02X, backup 0x%02X); clock starts at the built-in time. A flat supercap needs ~10 min of power to charge through the 3 kOhm trickle resistor.\n";
static const char LANG_CLOCK_NO_RTC_STARTS[] = "[clock] no RV-3028 RTC, the clock starts at the built-in time";
static const char LANG_CLOCK_VALUE_OUT_OF_RANGE[] = "[clock] value out of range, nothing changed";
static const char LANG_CLOSE_MENU[] = "Close menu";
static const char LANG_CONTEST1[] = "contest1";
static const char LANG_PCMTEXT[] = "pcmtext";
static const char LANG_CONTEST2[] = "contest2";
static const char LANG_CONTEST_BOTTOM_LINE_S[] = "[contest] bottom line: %s\n";
static const char LANG_CONTEST_FIRST_LINE[] = "Contest first line";
static const char LANG_PCM_TEXT[] = "PCM text";
static const char LANG_CONTEST_NUMBER[] = "Contest number";
static const char LANG_CONTEST_NUMBER_04D[] = "[contest] number: %04d\n";
static const char LANG_CONTEST_SECOND_LINE[] = "Contest second line";
static const char LANG_CONTEST_TOP_LINE_S[] = "[contest] top line: %s\n";
static const char LANG_CONTROL_D_D_S[] = "[control] %d/%d %s\n";
// BBC Test Card F/W's own photo window; short for the on-device menu,
// see UiText.CustomPhoto in the PC tool for the longer label.
static const char LANG_CUSTOM_PHOTO[] = "Custom photo";
static const char LANG_CONTROL_D_MIN_D_MAX[] = "[control] %d min=%d max=%d neutral=%d step=%d value=%d ";
static const char LANG_C_CONTEST_SET_THE[] = "   C       contest: set the number (always four digits)";
static const char LANG_C_SEND_ONE_OF[] = "   c       send one of the two faces, character by character";
static const char LANG_DATE_AND_TIME[] = "Date and time";
static const char LANG_DISABLED[] = "Disabled";
static const char LANG_DISPLAY_BRIGHTNESS[] = "Display brightness";
static const char LANG_DISPLAY_DX_D_ST7789P3_S[] = "[display] %dx%d ST7789P3: %s\n";
static const char LANG_DISPLAY_S[] = "[display] %s\n";
static const char LANG_DONE_CVBS_ON_J2[] = "    Done. CVBS on J2 pin 1 now comes from the pixel bus (P0-P7).";
static const char LANG_DOWNLOAD[] = "download";
static const char LANG_DOWNLOADING_S[] = "Downloading %.*s";
static const char LANG_DOWNLOAD_ABORTED_AT_LU_BYTES[] = "\n[download] aborted at %lu bytes: the port stopped taking data\n";
static const char LANG_DOWNLOAD_DONE[] = "[download] done";
static const char LANG_DOWNLOAD_READY_SEND_THE_SLOT[] = "[download] ready, send the slot number";
static const char LANG_DOWNLOAD_SLOT_D_IS_EMPTY[] = "[download] slot %d is empty\n";
static const char LANG_DOWNLOAD_SLOT_D_LU_BYTES[] = "[download] slot %d, %lu bytes, crc 0x%08lX, name \"%s\"\n";
static const char LANG_D_READ_A_SLOT[] = "   D       read a slot back over the port";
static const char LANG_D_TIMING_REPORT_ON[] = "   d       timing report on/off";
static const char LANG_EMPTY[] = "(empty)";
static const char LANG_EMPTY_SLOT[] = "Empty slot";
static const char LANG_ENABLED[] = "Enabled";
static const char LANG_ENABLE_CARD[] = "Enable card";
static const char LANG_ERASE[] = "erase";
static const char LANG_ERASE_ABORTED_CORE1_DID_NOT[] = "[erase] aborted: core1 did not stop, not safe to write";
static const char LANG_ERASE_DONE_SLOT_D_IS[] = "[erase] done, slot %d is empty\n";
static const char LANG_ERASE_ERASING_SLOT_D_THE[] = "[erase] erasing slot %d (the picture goes black meanwhile)\n";
static const char LANG_ERASE_FAILED_ON_SLOT_D[] = "[erase] failed on slot %d\n";
static const char LANG_ERASE_READY_SEND_THE_SLOT[] = "[erase] ready, send the slot number";
static const char LANG_ERASE_SLOT_D_WAS_ALREADY[] = "[erase] slot %d was already empty\n";
static const char LANG_ERASING_SLOT_D[] = "Erasing slot %d";
static const char LANG_ERROR_0X_02X_NOT[] = "    ERROR: 0x%02X not found on the bus.\n";
static const char LANG_ERROR_THE_ENCODER_DOES[] = "\nERROR: the encoder does not answer, video stays off.";
static const char LANG_E_EMPTY_A_SLOT[] = "   E       empty a slot";
static const char LANG_E_TELETEXT_ON_OFF[] = "   e       teletext on/off";
static const char LANG_FILTER_D_0X_02X_S[] = "[filter] %d = 0x%02X  %s\n";
static const char LANG_FIRST_LINE_COLOUR[] = "First line colour";
static const char LANG_FLASH_DIVISOR_U_AS[] = "Flash: divisor %u as the bootrom left it\n";
static const char LANG_FLASH_DIVISOR_U_QSPI[] = "   flash: divisor %u -> QSPI %lu.%lu MHz, measured at startup %u.%u MB/s (needs 22.5)\n";
static const char LANG_FLASH_DIVISOR_U_QSPI_2[] = "Flash: divisor %u -> QSPI %lu.%lu MHz, measured %u.%u MB/s (needs 22.5)\n";
static const char LANG_FLASH_LU_KB_TOTAL[] = "Flash: %lu kB total = %lu kB sketch + %lu kB reserved + %lu kB EEPROM\n";
static const char LANG_FONT[] = "font";
static const char LANG_FONT_D_ROWS_D_SX[] = "[font] %d rows=%d sx=%d sy=%d digits=%d gap=%d count=%d ";
static const char LANG_FONT_END[] = "[font] end";
static const char LANG_FONT_READY_SEND_THE_FACE[] = "[font] ready, send the face number";
static const char LANG_FONT_S_D_D_ON[] = "[font] %s (%d/%d) on %s\n";
static const char LANG_FOUND_0X_02X[] = "    Found: 0x%02X\n";
static const char LANG_FOUND_0X_02X_AFTER[] = "    Found: 0x%02X after %lu ms\n";
static const char LANG_F_FONT_PM5544_PM8546[] = "   f       font (PM5544/PM8546)";
static const char LANG_F_SETTINGS_BACK_TO[] = "   F       settings back to the factory values";
static const char LANG_G924_CHROMA_TEST_BARS_S[] = "[g924] chroma test bars %s\n";
static const char LANG_GLYPH_D_D[] = "[glyph] %d %d";
static const char LANG_G_REBOOT_INTO_THE[] = "   g       reboot into the USB bootloader, to flash new firmware";
static const char LANG_G_SWAP_BGR_AND[] = "          G swap BGR and RGB, V invert. Put the numbers in config.h.";
static const char LANG_HELP_KEYS[] = "[help] keys:";
static const char LANG_HELP_STATE_OF_THINGS[] = "[help] state of things:";
static const char LANG_H_G_V_B[] = "   H G V B display: other way up, BGR/RGB, invert, backlight the";
static const char LANG_H_THE_FIRST_TEXT[] = "   h       the first text line on this card, on or off";
static const char LANG_ID_FIRST_LINE_S_ON[] = "[id] first line %s on this card\n";
static const char LANG_ID_SECOND_LINE_S_ON[] = "[id] second line %s on this card\n";
static const char LANG_ID_S_HAS_NO_PLACE[] = "[id] %s has no place for the identification, nothing changed\n";
static const char LANG_ID_S_HAS_NO_PLACE_2[] = "[id] %s has no place for the second line, nothing changed\n";
static const char LANG_INPUT_FAILED_THE_LINE_IS[] = "[input] failed, the line is longer than %d characters; nothing was changed\n";
static const char LANG_INSERTLEFT[] = "insertleft";
static const char LANG_INSERTRIGHT[] = "insertright";
static const char LANG_INSERT_BOXES[] = "Insert boxes";
static const char LANG_INSERT_COLOUR[] = "Insert colour";
static const char LANG_INSERT_S[] = "[insert] %s\n";
static const char LANG_INTERNAL_COLOUR_BARS_S[] = "   internal colour bars %s\n";
static const char LANG_IS_TOO_NARROW_FOR[] = " is too narrow for teletext and ITS; they will not survive it";
static const char LANG_ITS[] = "ITS";
static const char LANG_ITS_S[] = "[ITS] %s\n";
static const char LANG_ITS_TAKES_LINES_SO[] = "            ITS takes lines, so %d of the %d packets drop out;\n            the last %d text rows are dropped\n";
static const char LANG_I_INSERTION_TEST_SIGNALS[] = "   I       insertion test signals on/off (lines 17, 18, 330, 331)";
static const char LANG_I_INSERT_BOXES_NONE[] = "   i       insert boxes: none / time / date and time";
static const char LANG_KNOB_CANDIDATE_TIMED_OUT_BACK[] = "[knob] candidate timed out, back to %d/%d\n";
static const char LANG_KNOB_D_D_S_PRESS[] = "[knob] %d/%d %s -- press to switch\n";
static const char LANG_KNOB_OFFERING_D_D_S[] = "[knob] offering %d/%d %s, press to switch\n";
static const char LANG_KNOB_TURN_TO_CHOOSE_A[] = "[knob] turn to choose a card, press to switch to it";
static const char LANG_K_SET_ONE_NAME[] = "   K       set one: name=value, or card.7.tickery=530";
static const char LANG_K_SHOW_THE_CLOCK[] = "   k       show the clock";
static const char LANG_LINE_MOVING_LINE_S_ON[] = "[line] moving line %s on %s\n";
static const char LANG_LINE_S_HAS_NO_PLACE[] = "[line] %s has no place for the moving line, nothing changed\n";
static const char LANG_LUMA[] = "[luma] ";
static const char LANG_L_DISPLAY_ALIGNMENT_PICTURE[] = "   L       display: alignment picture and what it is set to";
static const char LANG_L_DRAWS_THE_ALIGNMENT[] = "          L draws the alignment picture if it sits crooked.";
static const char LANG_L_LIST_THE_SIXTEEN[] = "   l       list the sixteen slots, one line each (for the PC tool)";
static const char LANG_MAKE_SURE_JP1_IS[] = "Make sure JP1 is on the DATA side (not towards the Y1 oscillator)!";
static const char LANG_MENU_CARD_OPEN[] = "[menu] card open\n";
static const char LANG_MENU_OPEN[] = "[menu] open\n";
static const char LANG_MENU_TIMED_OUT_CLOSED[] = "[menu] timed out, closed\n";
static const char LANG_MORE_THAN_D_STEPS[] = "more than %d steps";
static const char LANG_MOVING_LINE[] = "Moving line";
static const char LANG_M_THE_MOVING_LINE[] = "   m       the moving line on THIS card, on or off";
static const char LANG_NARROW_BARS_AT_X[] = "        narrow bars at x 7-53 and 660-688, picture rows\n        207-268; that is 4%% and 94%% of the width, so on a\n        cathode ray tube they may fall outside the picture\n";
static const char LANG_NONE[] = "(none)";
static const char LANG_NONE_EVERY_FILLED_SLOT[] = "(none, every filled slot)";
static const char LANG_NOTE_THE_VBI_IS[] = "            NOTE: the VBI is closed (key v), nothing comes out\n";
static const char LANG_NOTE_THE_VBI_IS_2[] = "      NOTE: the VBI is closed (key v), nothing comes out\n";
static const char LANG_NOTHING_ELSE_DOES_SO[] = "           (nothing else does, so the picture only blinks once;";
static const char LANG_NO_I2C_DEVICES_FOUND[] = "    NO I2C devices found!";
static const char LANG_N_TEXT_IN_THE[] = "   N       text in the top box (contest: top line)";
static const char LANG_N_THE_TICKER_ON[] = "   n       the ticker on THIS card: off, a bar of its own, over it";
static const char LANG_OFF[] = "off";
static const char LANG_OK[] = "    OK.";
static const char LANG_OK_ADV7391_FOUND_AT[] = "    OK: ADV7391 found at 0x%02X (ALSB=1 expected)\n";
static const char LANG_ON[] = "on";
static const char LANG_ONLY_ON_A_CARD[] = "           (only on a card that has a box for it; cards 1, 2 and 4 to 10 have)";
static const char LANG_ONLY_ON_THE_PM5644[] = "        (only on the PM5644 G924 test card)\n";
static const char LANG_ONLY_VISIBLE_ON_THE[] = "        (only visible on the PM5644 G00 test card)\n";
static const char LANG_ON_CAPS[] = "ON";
static const char LANG_OTHER_WAY_ROUND[] = "           other way round";
static const char LANG_O_O_COLUMN_1[] = "          o/O column -1/+1, j/J row -1/+1, H other way up,";
static const char LANG_O_O_J_J[] = "   o O j J display: column and row offset, minus and plus";
static const char LANG_PAL_SIGN_ADVANCED_CVBS[] = "=== PAL-sign, advanced CVBS PAL video generator ===";
static const char LANG_PHOTOGRAPH_SLOTS_CHECKED_IN[] = "Photograph slots checked in %lu ms\n";
static const char LANG_PHOTO_SLOT_D_CUSTOM_D[] = "[photo] slot %d (Custom %d): empty or invalid\n";
static const char LANG_PHOTO_SLOT_D_CUSTOM_D_2[] = "[photo] slot %d (Custom %d): \"%s\", %ux%u, crc 0x%08lX\n";
static const char LANG_PINS_P0_P7_ON[] = "Pins: P0..P7 on GP%u..GP%u, CLKIN GP%u, ~HSYNC GP%u, ~VSYNC GP%u, SFL GP%u, ~RESET GP%u, SDA GP%u, SCL GP%u\n";
static const char LANG_PM5544_WAS_TRACED_FROM[] = "        PM5544 was traced from a broadcast and has a fixed\n        width; PM8546 is Nimbus Sans Bold and Inter is\n        Inter Bold, both proportional\n";
static const char LANG_PRESS_ADJUST_HOLD_CLOSE[] = "Press=adjust Hold=close";
static const char LANG_PRESS_EDIT_HOLD_CLOSE[] = "Press=edit Hold=close";
static const char LANG_PRESS_NEXT_HOLD_CLOSE[] = "Press=next Hold=close";
static const char LANG_PRESS_PICK_HOLD_CLOSE[] = "Press=pick Hold=close";
static const char LANG_PRESS_SET_HOLD_CLOSE[] = "Press=set Hold=close";
static const char LANG_PRESS_TOGGLE_HOLD_CLOSE[] = "Press=toggle Hold=close";
static const char LANG_PSRAM_LU_KB_FOUND[] = "PSRAM: %lu kB found, not used by this program\n";
static const char LANG_PSRAM_NONE_FOUND[] = "PSRAM: none found\n";
static const char LANG_P_P_NEXT_PREVIOUS[] = "   p / P   next / previous test card";
static const char LANG_Q_THE_SECOND_TEXT[] = "   q       the second text line on this card, on or off";
static const char LANG_Q_THE_SLIDESHOW_SEQUENCE[] = "   Q       the slideshow sequence, as 2s:1/3s:12/1.5s:13";
static const char LANG_READ_0X_02X_EXPECTED[] = "    Read: 0x%02X (expected after reset: 0x%02X)\n";
static const char LANG_RESERVED_D_PHOTOGRAPH_SLOTS[] = "       reserved: %d photograph slots of %lu kB, %lu kB free for settings\n";
static const char LANG_RESET_CORE1_DID_NOT_PARK[] = "[reset] core1 did not park, photograph slots left untouched";
static const char LANG_RESET_D_PHOTOGRAPH_SLOT_S[] = "[reset] %d photograph slot(s) erased\n";
static const char LANG_RESET_FACTORY_SETTINGS_NOT_SAVED[] = "[reset] factory settings NOT saved (flash busy), try * once running";
static const char LANG_RESET_FACTORY_SETTINGS_SAVED_THE[] = "[reset] factory settings saved, the unit now starts like a new one";
static const char LANG_RESET_FACTORY_VALUES_LOADED_SAVING[] = "[reset] factory values loaded, saving once the bring-up allows it";
static const char LANG_RESET_PULSE_GIVEN_ON[] = "    RESET pulse given on GP%d\n";
static const char LANG_RESET_REBOOTING_INTO_THE_USB[] = "[reset] rebooting into the USB bootloader";
static const char LANG_RGB[] = "RGB";
static const char LANG_ROM_NOTE_D_WRONG_IN[] = "[rom] NOTE: %d wrong in the tables, first line %d sum %d\n";
static const char LANG_RUNNING[] = "RUNNING";
static const char LANG_R_HARDWARE_RESET_OF[] = "   R       hardware reset of the encoder";
static const char LANG_R_WRITE_THE_ENCODER[] = "   r       write the encoder configuration again";
static const char LANG_SCL[] = "SCL";
static const char LANG_SDA[] = "SDA";
static const char LANG_SECOND_LINE_COLOUR[] = "Second line colour";
static const char LANG_SEE_CARD_TRAIT_BOX[] = " -- see CARD_TRAIT_BOX in Firmware.ino";
static const char LANG_SEE_CARD_TRAIT_ID[] = " -- see CARD_TRAIT_ID in Firmware.ino";
static const char LANG_SEE_CARD_TRAIT_LINE[] = " -- see CARD_TRAIT_LINE in Firmware.ino";
static const char LANG_SEE_CARD_TRAIT_SUB[] = " -- see CARD_TRAIT_SUB in Firmware.ino";
static const char LANG_SEQ_CLEARED_THE_SLIDESHOW_TAKES[] = "[seq] cleared, the slideshow takes every filled slot again";
static const char LANG_SEQ_FAILED_S[] = "[seq] failed, %s\n";
static const char LANG_SEQ_FORM_2S_1_3S[] = "[seq] form 2s:1/3s:12/1.5s:13, an empty line clears it";
static const char LANG_SEQ_NOTE_STEP_D_IS[] = "[seq] note: step %d is card %d and that slot is empty, it shows grey\n";
static const char LANG_SEQ_NOW[] = "[seq] now ";
static const char LANG_SEQ_SET[] = "[seq] set ";
static const char LANG_SETTINGS_CHANGED_BUT_NOT[] = "   settings CHANGED but not written; key * does that";
static const char LANG_SEVEN_CARDS_HAVE_NO[] = "           (seven cards have no place for it and say so)";
static const char LANG_SFL_PULSE_NOT_CARRIED_OUT[] = "[sfl] pulse not carried out: no lines are going out, pin low again\n";
static const char LANG_SFL_PULSE_REQUESTED_TO_BE[] = "[sfl] pulse requested, to be aligned on the 625 -> 1 line boundary\n";
static const char LANG_SFL_TIMING_RESET_DONE_FIELD[] = "[sfl] timing reset done, field counter %u -> %u (0xBB bits[2:0])\n";
static const char LANG_SHOW[] = "SHOW";
static const char LANG_SHOW_FIRST_LINE[] = "Show first line";
static const char LANG_SHOW_SECOND_LINE[] = "Show second line";
static const char LANG_SLIDESHOW_S_SEQUENCE[] = "   slideshow %s, sequence ";
static const char LANG_SLIDE_NO_SEQUENCE_AND_NO[] = "[slide] no sequence and no filled photograph slots, nothing to show\n";
static const char LANG_SLIDE_OFF[] = "[slide] off\n";
static const char LANG_SLIDE_ON_D_STEPS[] = "[slide] on, %d steps\n";
static const char LANG_SLIDE_ON_EVERY_FILLED_SLOT[] = "[slide] on, every filled slot, %lu ms each\n";
static const char LANG_SLOTS_D_LU_D_D[] = "[slots] %d %lu %d %d\n";
static const char LANG_SLOTS_END[] = "[slots] end";
static const char LANG_SLOT_D_EMPTY[] = "[slot] %d empty\n";
static const char LANG_SLOT_D_FILLED_0X_08LX[] = "[slot] %d filled 0x%08lX %s\n";
static const char LANG_SRAM_LU_KB_ON[] = "SRAM:  %lu kB on the chip = %lu kB contiguous + %lu kB scratch; heap %d kB total, %d kB free\n";
static const char LANG_STARTING_ON_CARD_D[] = "Starting on card %d, %s\n";
static const char LANG_STARTS_ON_CARD_D[] = "   starts on card %d, %s\n";
static const char LANG_STEP_D_HAS_NO[] = "step %d has no time in front of it";
static const char LANG_STEP_D_HAS_NO_2[] = "step %d has no card number";
static const char LANG_STEP_D_IS_FOLLOWED[] = "step %d is followed by '%c' and not by /";
static const char LANG_STEP_D_IS_LONGER[] = "step %d is longer than the 65 s a step may last";
static const char LANG_STEP_D_IS_MISSING[] = "step %d is missing the : between time and card";
static const char LANG_STEP_D_LASTS_NO[] = "step %d lasts no time at all";
static const char LANG_STEP_D_NAMES_CARD[] = "step %d names card %d, there are %d";
static const char LANG_STORAGE_BACK_TO_THE_FACTORY[] = "[storage] back to the factory values from config.h\n";
static const char LANG_STORAGE_CHANGED_KEY_WRITES_IT[] = "[storage] changed, key * writes it to flash\n";
static const char LANG_STORAGE_JOURNAL_D_OF_D[] = "[storage] journal: %d of %d sectors put back to blank\n";
static const char LANG_STORAGE_NOTHING_HAS_CHANGED[] = "[storage] nothing has changed\n";
static const char LANG_STORAGE_SAVED[] = "[storage] saved\n";
static const char LANG_STORAGE_SAVED_S_QSPI_DIVISOR[] = "[storage] saved%s; QSPI divisor %u\n";
static const char LANG_STORAGE_SAVING_FAILED_NOTHING_IN[] = "[storage] SAVING FAILED -- nothing in flash was changed";
static const char LANG_STORAGE_SAVING_THE_CARD_FAILED[] = "[storage] SAVING THE CARD FAILED -- nothing in flash was changed";
static const char LANG_S_1F_IRE_S[] = "%s %+.1f IRE%s";
static const char LANG_S_2F_DB_S[] = "%s %+.2f dB%s";
static const char LANG_S_2F_DEGREES_S[] = "%s %+.2f degrees%s";
static const char LANG_S_2F_OF_FULL[] = "%s %+.2f %% of full scale%s";
static const char LANG_S_ABORTED[] = "[%s] aborted\n";
static const char LANG_S_ABORTED_NO_NUMBER[] = "[%s] aborted: no number received\n";
static const char LANG_S_ABORTED_S_IS[] = "[%s] aborted: \"%s\" is not a number\n";
static const char LANG_S_D_CLOCKS_D[] = "%s %d clocks (%d ns)%s";
static const char LANG_S_D_DOES_NOT[] = "[%s] %d does not exist, there are %d\n";
static const char LANG_S_ON_GP_2U[] = "    %s on GP%-2u: %s\n";
static const char LANG_S_SLIDESHOW_OF_THE[] = "   s       slideshow of the filled slots on and off";
static const char LANG_S_TEXT_IN_THE[] = "   S       text in the bottom box (contest: bottom line)";
static const char LANG_S_TYPE_AND_FINISH[] = "[%s] type and finish with Enter (Escape = cancel)\n";
static const char LANG_S_US_D[] = "%s%us:%d";
static const char LANG_S_U_02US_D[] = "%s%u.%02us:%d";
static const char LANG_S_U_03US_D[] = "%s%u.%03us:%d";
static const char LANG_S_U_US_D[] = "%s%u.%us:%d";
static const char LANG_TELETEXT_D[] = "teletext.%d";
static const char LANG_TELETEXT_S[] = "[teletext] %s\n";
static const char LANG_TELETEXT_WORKED_OUT_IN[] = "Teletext worked out in advance in %lu us\n";
static const char LANG_TEST_CARDS[] = "Test cards:";
static const char LANG_TEXTID[] = "textid";
static const char LANG_TEXTSUB[] = "textsub";
static const char LANG_TEXT_BOTTOM_BOX_S[] = "[text] bottom box: %s\n";
static const char LANG_TEXT_FONT[] = "Text font";
static const char LANG_TEXT_TOP_BOX_S[] = "[text] top box: %s\n";
static const char LANG_TEXT_TOP_S_BOTTOM[] = "   text top \"%s\", bottom \"%s\"%s\n";
static const char LANG_THE_DATA_IN_FLASH[] = "      The data in flash does not match the header. Run";
static const char LANG_THIS_LIST[] = "   ?       this list";
static const char LANG_TICKER[] = "Ticker";
static const char LANG_TICKERTEXT[] = "tickertext";
static const char LANG_TICKER_BAND_AT_ROW_D[] = "[ticker] band at row %d..%d\n";
static const char LANG_TICKER_COLOUR[] = "Ticker colour";
static const char LANG_TICKER_FONT[] = "Ticker font";
static const char LANG_TICKER_FONT_S_BAND_D[] = "[ticker] font %s, band %d rows at row %d\n";
static const char LANG_TICKER_SIZE[] = "Ticker size";
static const char LANG_TICKER_SPEED[] = "Ticker speed";
static const char LANG_TICKER_S_LU_BAND_ROWS[] = "[ticker] %s, %lu band rows, %lu us each on average, worst %lu us, %lu glyphs a row\n";
static const char LANG_TICKER_S_ON_S_S[] = "[ticker] %s on %s%s\n";
static const char LANG_TICKER_S_ON_THIS[] = "   ticker %s on this card, %s, band %d rows at row %d: ";
static const char LANG_TICKER_TEXT[] = "[ticker] text ";
static const char LANG_TICKER_Y[] = "Ticker Y";
static const char LANG_TIMED_OUT[] = "timed out";
static const char LANG_TIMING_MIN_LU_US_AVG[] = "[timing] min=%lu us  avg=%lu us  worst=%lu us  (budget %lu us)  over budget: %lu / %lu rows  starves=%lu  txstall=%lu  chain-restart=%lu  emergency-brake=%lu  flash-rows=%lu  load-stall=%lu  cfg-deviation=%lu\n";
static const char LANG_TIMING_WINDOW[] = "[timing] this window: %lu rows, avg=%lu us, worst=%lu us\n";
static const char LANG_TIMING_REPORT_IS_S[] = "Timing report is %s (key d).  ? lists every key.\n";
static const char LANG_TIMING_REPORT_S[] = "   timing report %s\n";
static const char LANG_TIMING_REPORT_S_BUILD_S[] = "[timing] report %s (build %s %s)\n";
static const char LANG_TOOLS_CONVERT_ROM_PATTERN[] = "      tools/convert_rom_pattern.py and build again.";
static const char LANG_TURN_CARD_PRESS_TOGGLE[] = "Turn=card Press=toggle Hold=close";
static const char LANG_TURN_LETTER_PRESS_NEXT[] = "Turn=letter Press=next Hold=save";
static const char LANG_TURN_VALUE_PRESS_HOLD[] = "Turn=value Press/Hold=done";
static const char LANG_TURN_VALUE_PRESS_NEXT[] = "Turn=value Press=next Hold=save";
static const char LANG_TXT[] = "TXT";
static const char LANG_T_SET_THE_CLOCK[] = "   T       set the clock: Tyyyy-mm-dd hh:mm:ss  or  Thh:mm:ss";
static const char LANG_UPLOADING_S[] = "Uploading %s";
static const char LANG_UPLOAD_ABORTED[] = "[upload] aborted";
static const char LANG_UPLOAD_ABORTED_AT_SECTOR_LU[] = "[upload] aborted at sector %lu: no more data\n";
static const char LANG_UPLOAD_ABORTED_CORE1_DID_NOT[] = "[upload] aborted: core1 did not stop, not safe to write";
static const char LANG_UPLOAD_ABORTED_NO_NAME_RECEIVED[] = "[upload] aborted: no name received";
static const char LANG_UPLOAD_DONE_CRC_0X_08LX[] = "[upload] done, crc 0x%08lX, name \"%s\", QSPI divisor %u\n";
static const char LANG_UPLOAD_ERASED[] = "[upload] erased";
static const char LANG_UPLOAD_ERASE_FAILED[] = "[upload] erase failed";
static const char LANG_UPLOAD_ERASING_THIS_TAKES_A[] = "[upload] erasing (this takes a while; the picture goes black meanwhile)";
static const char LANG_UPLOAD_HEADER_WRITE_FAILED_SLOT[] = "[upload] header write failed, slot stays invalid, crc 0x%08lX\n";
static const char LANG_UPLOAD_READY_LU_LU[] = "[upload] ready %lu %lu\n";
static const char LANG_UPLOAD_SEND_THE_NAME_ON[] = "[upload] send the name on one line, then the 4096 byte sectors";
static const char LANG_UPLOAD_SLOT_D_CUSTOM_D[] = "[upload] slot %d (Custom %d), name \"%s\"\n";
static const char LANG_UPLOAD_SLOT_D_DOES_NOT[] = "[upload] slot %d does not exist, there are %d\n";
static const char LANG_UPLOAD_SLOT_STAYS_INVALID_THE[] = "[upload] slot stays invalid; the header was not written";
static const char LANG_UPLOAD_SLOT_TOO_SMALL_LU[] = "[upload] slot too small: %lu of %lu bytes -- check board_build.filesystem_size\n";
static const char LANG_UPLOAD_WRITE_FAILED_AT_SECTOR[] = "[upload] write failed at sector %lu\n";
static const char LANG_USB[] = "USB";
static const char LANG_U_SHOW_WHAT_IS[] = "   U       show what is in the photograph slots";
static const char LANG_U_UPLOAD_A_PHOTOGRAPH[] = "   u       upload a photograph to Custom 1 through 16";
static const char LANG_VBI_VERTICAL_BLANKING_S[] = "[vbi] vertical blanking %s\n";
static const char LANG_V_VBI_OPEN_CLOSED[] = "   v       VBI open/closed (needed for test signals in the blanking)";
static const char LANG_WHICH_CARD_IS_ON[] = "            which card is on is the exception and goes in at once)";
static const char LANG_WRITE_THE_SETTINGS_TO[] = "   *       write the settings to flash";
static const char LANG_WRITTEN_0X_02X_READ[] = "    Written: 0x%02X, read back: 0x%02X\n";
static const char LANG_WSS[] = "WSS";
static const char LANG_W_ASPECT_RATIO_AND[] = "   w       aspect ratio and WSS";
static const char LANG_W_THE_TICKER_TEXT[] = "   W       the ticker text (up to 96 characters)";
static const char LANG_X_CHROMA_FILTER[] = "   x       chroma filter";
static const char LANG_X_SEND_A_CARD[] = "   X       send a card as a picture, 720x576 in 4:2:2";
static const char LANG_Y_Y_THE_TICKER[] = "   y Y     the ticker band up and down over the picture";
static const char LANG_Z_SFL_TIMING_RESET[] = "   z       SFL timing reset: eight field sequence to Field 1";
static const char LANG_Z_THE_TICKER_FONT[] = "   Z       the ticker font, and with it the height of the band";

// LUMA_FILTERS[]/CHROMA_FILTERS[] (adv7391.cpp): full reading and
// on-device short name per filter.
static const char LANG_FILTER_SSAF_FULL[] = "SSAF, flat to 5.5 MHz, then steep";
static const char LANG_FILTER_SSAF_SHORT[] = "SSAF";
static const char LANG_FILTER_LPF_PAL_FULL[] = "LPF PAL, flat to 4 MHz, -10 dB at 5.5 MHz";
static const char LANG_FILTER_LPF_PAL_SHORT[] = "LPF PAL";
static const char LANG_FILTER_NOTCH_PAL_FULL[] = "Notch PAL, notch at 4.4 MHz, flat above it";
static const char LANG_FILTER_NOTCH_PAL_SHORT[] = "Notch PAL";
static const char LANG_FILTER_LUMA_CIF_FULL[] = "Luma CIF, 3 dB down at 3.0 MHz";
static const char LANG_FILTER_CIF_SHORT[] = "CIF";
static const char LANG_FILTER_LUMA_QCIF_FULL[] = "Luma QCIF, falls off from 0 MHz, -10 dB at 2 MHz";
static const char LANG_FILTER_QCIF_SHORT[] = "QCIF";
static const char LANG_FILTER_1_3MHZ_FULL[] = "1.3 MHz, -10 dB at 1.8 MHz, -40 dB at 3.8 MHz";
static const char LANG_FILTER_1_3MHZ_SHORT[] = "1.3 MHz";
static const char LANG_FILTER_0_65MHZ_FULL[] = "0.65 MHz, -10 dB at 1.1 MHz, very steep";
static const char LANG_FILTER_0_65MHZ_SHORT[] = "0.65 MHz";
static const char LANG_FILTER_1_0MHZ_FULL[] = "1.0 MHz, -10 dB at 1.4 MHz";
static const char LANG_FILTER_1_0MHZ_SHORT[] = "1.0 MHz";
static const char LANG_FILTER_2_0MHZ_FULL[] = "2.0 MHz, flat to 2 MHz, -10 dB at 3.5 MHz";
static const char LANG_FILTER_2_0MHZ_SHORT[] = "2.0 MHz";
static const char LANG_FILTER_3_0MHZ_FULL[] = "3.0 MHz, flat to 2.5 MHz, -10 dB at 4 MHz";
static const char LANG_FILTER_3_0MHZ_SHORT[] = "3.0 MHz";

// PARAMS[] (adv7391.cpp): the analogue control names, sentence case,
// shown on the on-device menu and over the "[control]" serial line.
static const char LANG_PARAM_DAC_GAIN[] = "DAC gain";
static const char LANG_PARAM_Y_SCALE[] = "Y scale";
static const char LANG_PARAM_BRIGHTNESS[] = "Brightness";
static const char LANG_PARAM_HUE[] = "Hue";
static const char LANG_PARAM_LUMA_SSAF[] = "Luma SSAF";
static const char LANG_PARAM_LUMA_DELAY[] = "Luma delay";
static const char LANG_PARAM_CHROMA_DELAY[] = "Chroma delay";

// adv7391.cpp diagnostics: the bring-up self test's own verdicts.
static const char LANG_ADV_NEUTRAL_CONTROL_OFF[] = " (neutral, control off)";
static const char LANG_ADV_PULLUP_OK[] = "pull-up present, line idle -- OK";
static const char LANG_ADV_FLOATING[] =
    "FLOATING: no external pull-up, so no power on the "
    "ADV board or the wire is not there";
static const char LANG_ADV_HELD_LOW[] =
    "HELD LOW: a short to ground or a chip "
    "holding the bus";
static const char LANG_ADV_RESET_OK[] = "    OK: the chip answers and the RESET pin works.";
static const char LANG_ADV_RESET_WARNING[] =
    "    WARNING: unexpected value -> check the reset pin or the I2C timing.";
static const char LANG_ADV_RW_OK[] = "    OK: the read/write path works.";
static const char LANG_ADV_RW_ERROR[] = "    ERROR: mismatch!";
static const char LANG_ADV_SOFTRESET_OK[] = "    OK: the bit went back to 0.";
static const char LANG_ADV_SOFTRESET_WARNING[] = "    WARNING: the bit did not go back.";

// settings.cpp: the trait-mismatch warnings, one pair per trait.
static const char LANG_TRAIT_ID_SEEN[] = " draws the identification but is not listed as doing so";
static const char LANG_TRAIT_ID_NOT_SEEN[] = " is listed as drawing the identification but does not";
static const char LANG_TRAIT_BOX_SEEN[] = " draws insert boxes but is not listed as doing so";
static const char LANG_TRAIT_BOX_NOT_SEEN[] = " is listed as drawing insert boxes but does not";
static const char LANG_TRAIT_LINE_SEEN[] = " draws the moving line but is not listed as doing so";
static const char LANG_TRAIT_LINE_NOT_SEEN[] = " is listed as drawing the moving line but does not";
static const char LANG_TRAIT_SUB_SEEN[] = " draws the second line but is not listed as doing so";
static const char LANG_TRAIT_SUB_NOT_SEEN[] = " is listed as drawing the second line but does not";

// insertModeName() (settings.cpp).
static const char LANG_INSERT_NONE[] = "no date or time";
static const char LANG_INSERT_TIME[] = "time only";
static const char LANG_INSERT_DATE_TIME[] = "date and time";
static const char LANG_INSERT_TEXT[] = "fixed text";

// Assorted single-site status/caveat text (Firmware.ino).
static const char LANG_COPIED_IN_ONE_GO[] = "copied in one go";
static const char LANG_COPIED_IN_PIECES[] = "copied in pieces";
static const char LANG_EMPTY_SKIPPED_BY_P[] = "empty, skipped by p";
static const char LANG_NO_NAME[] = "(no name)";
static const char LANG_VBI_OPEN[] = "OPEN -- own VBI data on lines 7..22 comes out";
static const char LANG_VBI_CLOSED[] = "closed -- everything outside the active picture is blanked";
static const char LANG_JOURNAL_RING_WAS_FULL[] = " (the journal ring was full, one sector erased)";
static const char LANG_PORT_STOPPED_TAKING_DATA[] = "the port stopped taking data";
static const char LANG_NO_SPARE_TIME_TO_RENDER[] = "no spare time to render for ten seconds";
static const char LANG_KIND_CLOCK[] = "clock";
static const char LANG_KIND_TOP_BOX[] = "top box";
static const char LANG_KIND_SEQUENCE[] = "sequence";
static const char LANG_KIND_TICKER[] = "ticker";
static const char LANG_KIND_CFG[] = "cfg";
static const char LANG_KIND_BOTTOM_BOX[] = "bottom box";
static const char LANG_ID_NO_PLACE_ON_CARD[] = "  (this card has no place for it)";
static const char LANG_ID_OFF_ON_THIS_CARD[] = "  (OFF on this card, key h)";
static const char LANG_TRANSPARENT_NOT_ON_PHOTO[] = "  (transparent does not fit on a photograph)";

// The system-level on-device menu (MENU_TEXT_FIELDS/MENU_TOGGLES/
// MENU_CYCLES), separate from the per-card menu's cmAdd*() labels.
static const char LANG_MENU_FIRST_LINE[] = "First line";
static const char LANG_MENU_SECOND_LINE[] = "Second line";
static const char LANG_MENU_TICKER_TEXT[] = "Ticker text";
static const char LANG_MENU_TEXT_DATE[] = "Text date";
static const char LANG_MENU_TEXT_TIME[] = "Text time";
static const char LANG_MENU_TELETEXT[] = "Teletext";
static const char LANG_MENU_VBI[] = "VBI";
static const char LANG_MENU_AUTO_SUMMER_TIME[] = "Auto summer time";
static const char LANG_MENU_LUMA_FILTER[] = "Luma filter";
static const char LANG_MENU_CHROMA_FILTER[] = "Chroma filter";

// CARD_COLORS[] (Firmware.ino): the seven EBU colour-bar choices.
static const char LANG_COLOR_WHITE[] = "White";
static const char LANG_COLOR_YELLOW[] = "Yellow";
static const char LANG_COLOR_CYAN[] = "Cyan";
static const char LANG_COLOR_GREEN[] = "Green";
static const char LANG_COLOR_MAGENTA[] = "Magenta";
static const char LANG_COLOR_RED[] = "Red";
static const char LANG_COLOR_BLUE[] = "Blue";

// cmTickerModeName()'s NAMES[] (Firmware.ino).
static const char LANG_TICKMODE_OFF[] = "Off";
static const char LANG_TICKMODE_SOLID[] = "Solid";
static const char LANG_TICKMODE_TRANSPARENT[] = "Transparent";

// cmTickerSizeName()'s NAMES[] (Firmware.ino).
static const char LANG_TICKSIZE_EXTRA_SMALL[] = "Extra small";
static const char LANG_TICKSIZE_SMALL[] = "Small";
static const char LANG_TICKSIZE_MEDIUM[] = "Medium";
static const char LANG_TICKSIZE_LARGE[] = "Large";
static const char LANG_TICKSIZE_EXTRA_LARGE[] = "Extra large";

// The card names, one per testcards/*.cpp, shown on the display, in
// the Serial help listing and in the PC tool. Not moved:
// custom.cpp's PATTERN_CUSTOM##n, built from the preprocessor's own
// stringified slot number, a different literal per instantiation.
static const char LANG_CARD_EBU_BARS_RED[] = "EBU bars red";
static const char LANG_CARD_ATV_CONTEST[] = "ATV Contest";
static const char LANG_CARD_CROSSHATCH[] = "Crosshatch";
static const char LANG_CARD_EBU_BW[] = "EBU BW";
static const char LANG_CARD_FUBK_16X9[] = "FUBK 16:9";
static const char LANG_CARD_FUBK[] = "FUBK";
static const char LANG_CARD_SIMPLE_FUBK[] = "Simple FUBK";
static const char LANG_CARD_COLORBAR[] = "Colorbar";
static const char LANG_CARD_MIXED_BARS[] = "Mixed bars";
static const char LANG_CARD_MULTIBURST[] = "Multiburst";
static const char LANG_CARD_PICDREAM[] = "Picdream";
static const char LANG_CARD_PM5644[] = "PM5644";
static const char LANG_CARD_INDIAN_HEAD_BW[] = "Indian Head BW";
static const char LANG_CARD_PM5644_16X9[] = "PM5644 16:9";
static const char LANG_CARD_PULSE_AND_BAR[] = "Pulse & Bar";
static const char LANG_CARD_SINXX[] = "sin(x)/x";
static const char LANG_CARD_BBC_F[] = "BBC Card F";
static const char LANG_CARD_BBC_G[] = "BBC Card G";
static const char LANG_CARD_BBC_W[] = "BBC Card W";
static const char LANG_CARD_TVE[] = "TVE Card";
static const char LANG_CARD_PCM_AUDIO[] = "Ham PCM";
static const char LANG_CARD_SONY_PCM[] = "Sony PCM";
static const char LANG_RESOLUTION[] = "Resolution";
static const char LANG_14_BIT[] = "14 bit";
static const char LANG_16_BIT[] = "16 bit";
static const char LANG_PRE_EMPHASIS[] = "Pre-emphasis";
static const char LANG_CTRL_IN_PICTURE[] = "Ctrl in picture";
static const char LANG_HAM_QUALITY[] = "Quality";
static const char LANG_HAM_HQ[] = "HQ 48k 14 bit";
static const char LANG_HAM_LQ[] = "LQ 32k 12 bit";
static const char LANG_HAM_VOICE[] = "Voice A-law";
static const char LANG_HAM_NARROW[] = "Narrow";

// display.cpp: the two full-panel hint lines, the splash text, and
// displayReport()'s own status line (a debug key's answer, not
// protocol, but still text a human reads).
static const char LANG_DISP_HINT_CANDIDATE[] = "Press button to select";
static const char LANG_DISP_HINT_BUSY[] = "please wait";
static const char LANG_DISP_REPORT_FMT[] =
    "col %d, row %d, madctl 0x%02X (%s), invert %s, backlight %s and active %s, %d Hz on "
    "SPI%d";
static const char LANG_BGR[] = "BGR";
static const char LANG_HIGH[] = "high";
static const char LANG_LOW[] = "low";
static const char LANG_SPLASH_TITLE[] = "CVBS PAL generator";
static const char LANG_SPLASH_NAME[] = "PAL-sign";
static const char LANG_SPLASH_RESTORING_DEFAULTS[] = "Restoring defaults";
static const char LANG_SPLASH_RELEASE_TO_CANCEL[] = "Release to cancel";
static const char LANG_SPLASH_PLEASE_WAIT[] = "Please wait...";
static const char LANG_NO_DISPLAY_IN_THIS_BUILD[] = "no display in this build";

#endif  // LANGUAGE_H
