// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// scki_clock //
// ---------- //

#define scki_clock_wrap_target 0
#define scki_clock_wrap 1
#define scki_clock_pio_version 0

static const uint16_t scki_clock_program_instructions[] = {
            //     .wrap_target
    0xa042, //  0: nop                    side 0
    0xb042, //  1: nop                    side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program scki_clock_program = {
    .instructions = scki_clock_program_instructions,
    .length = 2,
    .origin = -1,
    .pio_version = scki_clock_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config scki_clock_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + scki_clock_wrap_target, offset + scki_clock_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

// ------ //
// i2s_rx //
// ------ //

#define i2s_rx_wrap_target 1
#define i2s_rx_wrap 19
#define i2s_rx_pio_version 0

static const uint16_t i2s_rx_program_instructions[] = {
    0xe041, //  0: set    y, 1
            //     .wrap_target
    0x208a, //  1: wait   1 gpio, 10
    0x200a, //  2: wait   0 gpio, 10
    0x2009, //  3: wait   0 gpio, 9
    0x2089, //  4: wait   1 gpio, 9
    0xe03e, //  5: set    x, 30
    0x2009, //  6: wait   0 gpio, 9
    0x2089, //  7: wait   1 gpio, 9
    0x4001, //  8: in     pins, 1
    0x0046, //  9: jmp    x--, 6
    0x4061, // 10: in     null, 1
    0x208a, // 11: wait   1 gpio, 10
    0x2009, // 12: wait   0 gpio, 9
    0x2089, // 13: wait   1 gpio, 9
    0xe03e, // 14: set    x, 30
    0x2009, // 15: wait   0 gpio, 9
    0x2089, // 16: wait   1 gpio, 9
    0x4001, // 17: in     pins, 1
    0x004f, // 18: jmp    x--, 15
    0x4041, // 19: in     y, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program i2s_rx_program = {
    .instructions = i2s_rx_program_instructions,
    .length = 20,
    .origin = -1,
    .pio_version = i2s_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config i2s_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2s_rx_wrap_target, offset + i2s_rx_wrap);
    return c;
}
#endif

