// GENERATED by tools/convert_rom_pattern.py -- do not edit by hand.
//
// EBU bars and red
// Variants: -
//   fully drawn; BT.471 75 percent bars, white at 100 percent
#pragma once

#include <stdint.h>

static const int BARSRED_UNIQUE_LINES = 2;
static const int BARSRED_RUN_COUNT = 10;
static const int BARSRED_PAL_SIZE = 8;

// The picture sits centred in the 720 samples that BT.656 carries, with
// 0 black samples in front of it on every line. Written down here as a
// fact about the tables; the renderer does not need it, because the
// black is already in the run lengths.

// These tables live in flash. The renderer does NOT read them directly:
// rompattern.cpp copies the active picture to RAM at startup, because
// pulling separate streams out of flash per line costs more time than
// drawing the whole pattern (XIP cache misses).
extern "C" {
extern const uint32_t barsred_pal[];    // palette: one pixel pair per entry
extern const uint16_t barsred_idx[];    // palette index per run
extern const uint8_t barsred_len[];     // repeat count per run (1..255)
extern const uint32_t barsred_start[];  // first run per unique line (plus a closing value)
extern const uint16_t barsred_line[];   // [variant][row] -> unique line
}
