// GENERATED by tools/convert_rom_pattern.py -- do not edit by hand.
//
// FUBK 4:3 without the circle
// Variants: fubk_4x3.bin
//   as the FUBK 4:3, but without the centre circle and without the centre line in the text box; built by tools/make_fubk_nocircle.py
#pragma once

#include <stdint.h>

static const int FUBKNOCIRCLE_UNIQUE_LINES = 266;
static const int FUBKNOCIRCLE_RUN_COUNT = 30465;
static const int FUBKNOCIRCLE_PAL_SIZE = 1174;

// The picture sits centred in the 720 samples that BT.656 carries, with
// 0 black samples in front of it on every line. Written down here as a
// fact about the tables; the renderer does not need it, because the
// black is already in the run lengths.

// These tables live in flash. The renderer does NOT read them directly:
// rompattern.cpp copies the active picture to RAM at startup, because
// pulling separate streams out of flash per line costs more time than
// drawing the whole pattern (XIP cache misses).
extern "C" {
extern const uint32_t fubknocircle_pal[];    // palette: one pixel pair per entry
extern const uint16_t fubknocircle_idx[];    // palette index per run
extern const uint8_t fubknocircle_len[];     // repeat count per run (1..255)
extern const uint32_t fubknocircle_start[];  // first run per unique line (plus a closing value)
extern const uint16_t fubknocircle_line[];   // [variant][row] -> unique line
}
