// Colour bars generated by the encoder's own internal generator
// (register 0x84 bit 6, "SD Color Bars", ADV7391 table 24 p.35),
// not from picture data. Useful for splitting the chain: if these bars
// work but another card does not, the fault is upstream of the encoder.
#include "../display.h"
#include "../gfx.h"
#include "../language.h"
#include "../pattern.h"

// The encoder makes this picture itself with no readback path, so the
// status display's miniature can't be sampled here like every other
// card; it draws a likeness instead (75% ITU-R BT.471-1 bars, same as
// "EBU bars and red"), not a measurement of the real output.
static const uint8_t THUMB_BARS[8][3] = {
    {255, 255, 255},  // white, at 100 percent
    {191, 191, 0},    // yellow
    {0, 191, 191},    // cyan
    {0, 191, 0},      // green
    {191, 0, 191},    // magenta
    {191, 0, 0},      // red
    {0, 0, 191},      // blue
    {0, 0, 0},        // black
};

static void internbarInit() {
  displayThumbHold(true);
  // Every row is identical; draw the top row and copy it down.
  for (int x = 0; x < DISP_THUMB_W; x++) {
    const uint8_t *c = THUMB_BARS[(x * 8) / DISP_THUMB_W];
    displayThumbPixel(x, 0, c[0], c[1], c[2]);
  }
  for (int y = 1; y < DISP_THUMB_H; y++) displayThumbCopyRow(y, 0);
}

static void internbarRenderRow(uint8_t *base, int y) {
  (void)y;
  uint32_t *w = (uint32_t *)base;
  for (int i = 0; i < SCREEN_W / 2; i++) *w++ = 0x10801080u;  // Cb,Y,Cr,Y: black
}

const Pattern PATTERN_INTERNBAR = {LANG_CARD_COLORBAR, internbarInit,
                                   internbarRenderRow, nullptr, false, true};
