// GENERATED by tools/convert_rom_pattern.py -- do not edit by hand.
//
// PM5644 (G913)
// Variants: PM5644G913_pat0
//   monoscope with the Indian head; monochrome, no text boxes
#pragma once

#include <stdint.h>

static const int PM5644G913_UNIQUE_LINES = 561;
static const int PM5644G913_RUN_COUNT = 67390;
static const int PM5644G913_PAL_SIZE = 2208;

// The picture sits centred in the 720 samples that BT.656 carries, with
// 6 black samples in front of it on every line. Written down here as a
// fact about the tables; the renderer does not need it, because the
// black is already in the run lengths.

// These tables live in flash. The renderer does NOT read them directly:
// rompattern.cpp copies the active picture to RAM at startup, because
// pulling separate streams out of flash per line costs more time than
// drawing the whole pattern (XIP cache misses).
extern "C" {
extern const uint32_t pm5644g913_pal[];    // palette: one pixel pair per entry
extern const uint16_t pm5644g913_idx[];    // palette index per run
extern const uint8_t pm5644g913_len[];     // repeat count per run (1..255)
extern const uint32_t pm5644g913_start[];  // first run per unique line (plus a closing value)
extern const uint16_t pm5644g913_line[];   // [variant][row] -> unique line
}
