// GENERATED by tools/convert_rom_pattern.py -- do not edit by hand.
//
// sin(x)/x
// Variants: sin_x_x_pal.bin
//   test signal, monochrome
#pragma once

#include <stdint.h>

static const int SINXX_UNIQUE_LINES = 3;
static const int SINXX_RUN_COUNT = 271;
static const int SINXX_PAL_SIZE = 95;

// The picture sits centred in the 720 samples that BT.656 carries, with
// 0 black samples in front of it on every line. Written down here as a
// fact about the tables; the renderer does not need it, because the
// black is already in the run lengths.

// These tables live in flash. The renderer does NOT read them directly:
// rompattern.cpp copies the active picture to RAM at startup, because
// pulling separate streams out of flash per line costs more time than
// drawing the whole pattern (XIP cache misses).
extern "C" {
extern const uint32_t sinxx_pal[];    // palette: one pixel pair per entry
extern const uint16_t sinxx_idx[];    // palette index per run
extern const uint8_t sinxx_len[];     // repeat count per run (1..255)
extern const uint32_t sinxx_start[];  // first run per unique line (plus a closing value)
extern const uint16_t sinxx_line[];   // [variant][row] -> unique line
}
