// GENERATED by tools/convert_rom_pattern.py -- do not edit by hand.
//
// BBC Test Card G
// Variants: PM5644G00_pat2 + Test Card G parameters
//   derived from the PM5644 G00 EPROM tables by tools/make_testcardg.py: colour bars, block wave and bottom segment lifted 25 percent, multiburst redrawn at 71.4 percent with the PAL-I frequency set
#pragma once

#include <stdint.h>

static const int TESTCARDG_UNIQUE_LINES = 484;
static const int TESTCARDG_RUN_COUNT = 55509;
static const int TESTCARDG_PAL_SIZE = 1814;

// The picture sits centred in the 720 samples that BT.656 carries, with
// 6 black samples in front of it on every line. Written down here as a
// fact about the tables; the renderer does not need it, because the
// black is already in the run lengths.

// These tables live in flash. The renderer does NOT read them directly:
// rompattern.cpp copies the active picture to RAM at startup, because
// pulling separate streams out of flash per line costs more time than
// drawing the whole pattern (XIP cache misses).
extern "C" {
extern const uint32_t testcardg_pal[];    // palette: one pixel pair per entry
extern const uint16_t testcardg_idx[];    // palette index per run
extern const uint8_t testcardg_len[];     // repeat count per run (1..255)
extern const uint32_t testcardg_start[];  // first run per unique line (plus a closing value)
extern const uint16_t testcardg_line[];   // [variant][row] -> unique line
}
