// GENERATED by tools/convert_rom_pattern.py -- do not edit by hand.
//
// BBC Test Card W
// Variants: -
//   16:9; card drawn, photograph and letter from a reference
#pragma once

#include <stdint.h>

static const int TESTCARDW_UNIQUE_LINES = 538;
static const int TESTCARDW_RUN_COUNT = 40977;
static const int TESTCARDW_PAL_SIZE = 1652;

// The picture sits centred in the 720 samples that BT.656 carries, with
// 0 black samples in front of it on every line. Written down here as a
// fact about the tables; the renderer does not need it, because the
// black is already in the run lengths.

// These tables live in flash. The renderer does NOT read them directly:
// rompattern.cpp copies the active picture to RAM at startup, because
// pulling separate streams out of flash per line costs more time than
// drawing the whole pattern (XIP cache misses).
extern "C" {
extern const uint32_t testcardw_pal[];    // palette: one pixel pair per entry
extern const uint16_t testcardw_idx[];    // palette index per run
extern const uint8_t testcardw_len[];     // repeat count per run (1..255)
extern const uint32_t testcardw_start[];  // first run per unique line (plus a closing value)
extern const uint16_t testcardw_line[];   // [variant][row] -> unique line
}
