import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
                                Preformatted, PageBreak, KeepTogether)

# Written next to this script; copy it wherever it needs to go.
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Ham PCM specification.pdf")

ss = getSampleStyleSheet()
body = ParagraphStyle('body', parent=ss['Normal'], fontName='Helvetica', fontSize=10, leading=14, spaceAfter=6)
h1 = ParagraphStyle('h1', parent=ss['Heading1'], fontName='Helvetica-Bold', fontSize=16, spaceBefore=14, spaceAfter=8)
h2 = ParagraphStyle('h2', parent=ss['Heading2'], fontName='Helvetica-Bold', fontSize=12, spaceBefore=10, spaceAfter=6)
title = ParagraphStyle('title', parent=ss['Title'], fontName='Helvetica-Bold', fontSize=20, spaceAfter=4)
sub = ParagraphStyle('sub', parent=body, textColor=colors.HexColor('#555555'), fontSize=10, spaceAfter=14)
code = ParagraphStyle('code', parent=ss['Code'], fontName='Courier', fontSize=8.2, leading=10.5,
                      backColor=colors.HexColor('#F3F3F3'), borderPadding=4, spaceBefore=4, spaceAfter=8)
bul = ParagraphStyle('bul', parent=body, leftIndent=12, bulletIndent=2, spaceAfter=3)

def P(t, s=body): return Paragraph(t, s)
def B(t): return Paragraph(t, bul, bulletText='\u2022')
def C(t): return Preformatted(t, code)

cell = ParagraphStyle('cell', parent=body, fontSize=9, leading=11.5, spaceAfter=0)
cellb = ParagraphStyle('cellb', parent=cell, fontName='Helvetica-Bold')

def table(rows, widths, header=True):
    rows = [[Paragraph(c, cellb if (header and i == 0) else cell) for c in r] for i, r in enumerate(rows)]
    t = Table(rows, colWidths=widths)
    st = [('FONT', (0, 0), (-1, -1), 'Helvetica', 9),
          ('GRID', (0, 0), (-1, -1), 0.4, colors.HexColor('#999999')),
          ('VALIGN', (0, 0), (-1, -1), 'TOP'),
          ('TOPPADDING', (0, 0), (-1, -1), 3), ('BOTTOMPADDING', (0, 0), (-1, -1), 3)]
    if header:
        st += [('FONT', (0, 0), (-1, 0), 'Helvetica-Bold', 9),
               ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#E4E4E4'))]
    t.setStyle(TableStyle(st))
    return t

doc = SimpleDocTemplate(OUT, pagesize=A4, leftMargin=20*mm, rightMargin=20*mm, topMargin=18*mm, bottomMargin=18*mm,
                        title="Ham PCM specification", author="PE5PVB (PAL-sign)")
S = []
S.append(P("Ham PCM", title))
S.append(P("Digital stereo audio in a PAL composite video signal, as generated by the PAL-sign "
           "test pattern generator. Line code version 3. Specification version 2.0, 30 August 2026 "
           "(change log in section 12). For anyone who wants to decode it, for example in OpenScope.", sub))

S.append(P("1. Overview", h1))
S.append(P("Ham PCM carries 48 kHz, 14 bit stereo PCM audio in the active picture of a normal 625 line, "
           "50 Hz interlaced PAL video signal, the way the Sony PCM-F1 family did, but with a line code of "
           "its own designed for an FM amateur-television link: short interference (sparkles of a few bits) "
           "and thermal noise should cost as little as possible, and latency stays at one video line. "
           "Every video row is independent: it contains a number of complete stereo sample pairs, a "
           "Reed-Solomon protected core, a CRC checked refinement and, spread over 30 rows, a 10 character "
           "text. Nothing is interleaved across rows."))
S.append(P("The picture is black-and-white: the chroma subcarrier and colour burst are switched off in the "
           "encoder, and each bit is a 696/180 = 3.87 pixel wide luma level, white for 1 and black for 0 (NRZ). There is no "
           "WSS, teletext or other VBI data on this card."))

S.append(P("2. Video layout", h1))
S.append(table([
    ["Item", "Value"],
    ["Video standard", "PAL B/G, 625 lines, 50 Hz, interlaced; BT.601 raster, 720 active pixels a line at 13.5 MHz"],
    ["Rows carrying audio", "All 576 active rows (frame rows 0..575, lines 23..310 and 336..623) except the text band, see below"],
    ["Text band", "Frame rows 260..291 (32 rows, 16 a field) show the card's caption in white on black and carry no audio "
                  "and no run-in; a decoder simply finds no run-in there"],
    ["Rows 0 and 1", "Structured like every other row but always carry 0 pairs (n = 0): a capture card in PAL mode "
                     "delivers its 576 rows one line late, so these two rows never reach it"],
    ["Bit cell", "696/180 = 3.867 px (286.4 ns); bit k starts at pixel 12 + floor((696 k + 90) / 180)"],
    ["Levels", "1 = white (Y = 235, 100 % white), 0 = black (Y = 16, blanking level); NRZ, no return to zero"],
    ["Bits a row", "180, in the middle 696 of the 720 active pixels; the first and last 12 pixels are black guards"],
    ["Bit order", "Left to right = first to last; bytes MSB first"],
    ["Colour", "Chroma and burst off (luma only)"],
], [40*mm, 130*mm]))
S.append(Spacer(1, 4))
S.append(P("Sample order: the generator renders field 1 (even frame rows, top to bottom) and then field 2 (odd "
           "frame rows, top to bottom), and each row takes whatever samples the ADC delivered at that moment. "
           "A decoder must therefore concatenate the rows <b>in field order</b>, not in frame (interleaved) order; "
           "reading the de-interlaced frame top to bottom alternates between two moments 20 ms apart and plays "
           "a pure tone an octave low. Within a row the pairs are in time order."))
S.append(P("Rate: the ADC delivers 48000 pairs a second, 3.07 a row, so rows carry 3 or 4 pairs (n varies; a row "
           "can also carry 0..2 after the text band or a field blanking has parked samples). A decoder plays the "
           "pairs as they come; the average is exactly 48000 a second, locked to the video clock."))

S.append(P("3. Row structure (180 bits)", h1))
S.append(table([
    ["Bits", "Field", "Content"],
    ["0..7", "Run-in", "8 alternating bits 10101010 or 01010101: the polarity flips every other row of a field "
                       "((row >> 1) & 1, frame row numbering). Use it for bit phase and slicing threshold "
                       "(threshold = (min + max) / 2 of the run-in)."],
    ["8..11", "Guard", "4 bits of 0: lets the video filter settle before the sync byte"],
    ["12..19", "Sync", "0x2E = 00101110"],
    ["20..123", "Core codeword", "13 bytes, RS(13,9): header, 8 core bytes (scrambled), 4 parity bytes"],
    ["124..171", "Refinement", "6 bytes (scrambled): the low 6 bits of the 8 samples, 48 bits"],
    ["172..179", "CRC", "CRC-8 over the 6 scrambled refinement bytes"],
], [22*mm, 28*mm, 120*mm]))
S.append(Spacer(1, 4))
S.append(P("Byte order after the sync byte, 20 bytes: H C0 C1 C2 C3 C4 C5 C6 C7 P0 P1 P2 P3 E0 E1 E2 E3 E4 E5 CRC."))

S.append(P("3.1 The header byte H", h2))
S.append(table([
    ["Bit", "Meaning"],
    ["7..6", "Always 11 (0xC0): the format marker, also a check against RS miscorrection"],
    ["5", "Text marker: 1 on the first of the 30 rows of a text cycle, else 0"],
    ["4..3", "Two bits of the text channel, see section 6"],
    ["2..0", "n = number of stereo pairs in this row, 0..4"],
], [22*mm, 148*mm]))

S.append(P("3.2 Samples: core and refinement", h2))
S.append(P("Each sample is 14 bit two's complement (the ADC's 16 bit sample arithmetically shifted right by 2). "
           "The 8 sample slots of a row are, in order, L0 R0 L1 R1 L2 R2 L3 R3; slots beyond n are zero. "
           "Sample s (taken as a 14 bit unsigned pattern, s &amp; 0x3FFF) is split into"))
S.append(B("core byte = (s &gt;&gt; 6) &amp; 0xFF, the top 8 bits (bit 13, the sign, is the MSB of the core byte);"))
S.append(B("refinement = s &amp; 0x3F, the low 6 bits."))
S.append(P("Core bytes C0..C7 follow the slot order. The 8 refinements are packed MSB first into a 48 bit string, "
           "slot 0 first, and that string forms E0..E5 (E0 holds refinement 0 and the top 2 bits of refinement 1, "
           "and so on). Reconstruction: s = (core &lt;&lt; 6) | refinement, then sign-extend from bit 13; to 16 bit: "
           "shift left by 2."))

S.append(P("3.3 Scrambling", h2))
S.append(P("Core bytes and refinement bytes are XORed with a fixed 14 byte keystream before the parity and CRC are "
           "computed, so silence is not a long flat run. The key is the same for every row: byte i of the key "
           "scrambles Ci (i = 0..7) and byte 8 + j scrambles Ej (j = 0..5). The header and the parity bytes are "
           "not scrambled. The keystream comes from a 16 bit Fibonacci LFSR, x^16 + x^14 + x^13 + x^11 + 1, "
           "seed 0xACE1, one output bit a step (the bit shifted out), packed MSB first into bytes:"))
S.append(C("lfsr = 0xACE1\n"
           "for each key byte:  k = 0\n"
           "    repeat 8 times:  bit = lfsr & 1;  lfsr = (lfsr >> 1) ^ (bit ? 0xB400 : 0);  k = (k << 1) | bit\n"
           "    key byte = k\n"
           "\n"
           "KEY = 87 23 46 DC B0 DD EE F8  FD C3 5C BF 5C 53   (hex, bytes 0..13)"))
S.append(P("A decoder can simply use the 14 constant bytes."))

S.append(P("4. Reed-Solomon code RS(13,9)", h1))
S.append(P("Field: GF(256) with the primitive polynomial x^8 + x^4 + x^3 + x^2 + 1 (0x11D), primitive element "
           "alpha = 2. Generator polynomial with roots alpha^0 .. alpha^3:"))
S.append(C("g(x) = (x - 1)(x - a)(x - a^2)(x - a^3) = x^4 + 15 x^3 + 54 x^2 + 120 x + 64   (coefficients in GF(256))"))
S.append(P("The codeword is systematic. Message m(x) = H x^8 + C0 x^7 + ... + C7 (9 bytes, header first, highest "
           "degree first); the parity is the remainder of m(x) x^4 divided by g(x); the transmitted codeword is "
           "c(x) = m(x) x^4 + parity, 13 bytes, coefficient of x^12 (the header) first, P3 = coefficient of x^0 last. "
           "Encoder as a shift register:"))
S.append(C("rem[0..3] = 0\n"
           "for each message byte d (H, then C0..C7, scrambled):\n"
           "    fb = d ^ rem[0];  rem = rem[1], rem[2], rem[3], 0\n"
           "    if fb != 0: for j in 0..3: rem[j] ^= gmul(g[j+1], fb)      # g = [1, 15, 54, 120, 64]\n"
           "P0..P3 = rem[0..3]"))
S.append(P("Syndromes S_i = c(alpha^i), i = 0..3, evaluated over the 13 bytes highest degree first (Horner). "
           "All four zero means a clean codeword. The code corrects any 2 byte errors, or up to 4 erasures "
           "(byte positions known to be doubtful), or 1 error plus 2 erasures. Because the code is tiny, the "
           "reference decoder works by trial rather than Berlekamp-Massey: for every candidate set of error "
           "positions (the erasures plus 0, 1 or 2 further positions, 78 pairs at most) solve the Vandermonde "
           "system S_i = sum_j Y_j X_j^i for the magnitudes Y_j by Gaussian elimination over GF(256), with "
           "X_j = alpha^(12 - p_j) for byte position p_j (0 = header); the first set for which all four "
           "equations agree gives the correction. Any standard RS decoder with these parameters works too. "
           "After decoding, check that bits 7..6 of the header are 11 and n is at most 4; otherwise treat the "
           "row as lost (with three or more errors the code occasionally miscorrects; the reference measured "
           "3 in 20000 such rows passing that check)."))

S.append(P("5. CRC-8 of the refinement", h1))
S.append(P("Polynomial x^8 + x^2 + x + 1 (0x07), initial value 0, no reflection, no final XOR, over the 6 "
           "scrambled refinement bytes E0..E5 in order (the plain CRC-8/ATM style):"))
S.append(C("c = 0\n"
           "for each byte d: c ^= d; repeat 8 times: c = (c & 0x80) ? ((c << 1) ^ 0x07) & 0xFF : (c << 1) & 0xFF"))
S.append(P("If the CRC does not match, discard the refinement and play the row from the core bytes alone "
           "(refinement = 0, or 32 for a mid-tread guess): 8 bit audio for that row, no hole. The CRC passes "
           "a damaged refinement 1 time in 256, which costs at most a small click."))

S.append(P("6. Text channel", h1))
S.append(P("Header bits 5..3 carry a 10 character text, 6 bits a character, 60 bits, sent 2 bits a row over 30 "
           "consecutive rows (in the generator's row order, field by field) and then repeated; a cycle takes "
           "about 2 ms. Bit 5 of the header is 1 on the first row of a cycle only. The 60 bit string is the 10 "
           "characters MSB first, and bits 4..3 of row k of the cycle (k = 0..29) are bits 59 - 2k and 58 - 2k of "
           "that string. Characters index this 64 symbol alphabet (index 0 = space):"))
S.append(C(' ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,-/:;!?\'()+=&@#*%<>"_[]{}|'))
S.append(P("Decoding: on a header with bit 5 set start a new cycle; collect bits 4..3 of it and of the 29 rows "
           "that follow; if any row in between is lost, drop the cycle and wait for the next marker. Trailing "
           "spaces are padding. The text sits inside the RS codeword, so it is as protected as the audio."))

S.append(P("7. Decoding, step by step", h1))
for t in [
    "Take the 720 active luma pixels of a row. Search the first ~36 pixels for the run-in: 7 consecutive "
    "samples one bit period apart alternating around their own (min + max) / 2 with enough swing (the reference "
    "demands 40 levels), either polarity. Keep the threshold.",
    "Find the sync byte: 4 low guard bits followed by 0x2E, allowing at most one wrong bit, searching a few "
    "pixels either way of the nominal position (run-in start + 12 bits) and a small period correction. "
    "Capture cards regenerate their own pixel clock; the reference measures the nominal period steadily but "
    "searches 3.4 .. 4.6.",
    "Slice the 160 bits after the sync byte at the bit centres into 20 bytes. Optionally remember, per byte, "
    "how close its bits came to the threshold: the bytes with the smallest margin are the erasure candidates.",
    "Decode the 13 byte core codeword (errors only; if that fails and there are clearly doubtful bytes, "
    "retry with the two, then four, weakest as erasures). Check header bits 7..6 = 11 and n <= 4.",
    "Unscramble C0..C7 with key bytes 0..7. Check the CRC of E0..E5; if good, unscramble them with key bytes "
    "8..13 and unpack the 6 bit refinements, else use zero refinements.",
    "Rebuild the n pairs (L, R) as 14 bit two's complement, shift to 16 bit, and append them to the audio stream "
    "in field order. Feed the text channel from the header.",
    "A row whose core cannot be decoded is a hole of about 3 pairs: interpolate linearly from the last good "
    "pair to the first pair of the next good row (one row of extra latency, for the hole only); after a "
    "handful of lost rows hold the last value instead so a fade does not pile up latency.",
]:
    S.append(B(t))

S.append(P("8. Worked example", h1))
S.append(P("Pairs (L, R) = (1000, -1000), (2047, -2048), (0, -1), (123, 456), n = 4; text marker set and text bits "
           "01 (the first row of a cycle for the text \"PE5PVB\", whose first character P = index 16 = 010000, so "
           "bits 59..58 are 01). The 20 bytes after the sync byte are:"))
S.append(C("EC 88 D3 59 3C B0 22 EF FF 74 F9 FE 23  5C 4C 9C BC A2 9B  09\n"
           "H  C0 C1 C2 C3 C4 C5 C6 C7 P0 P1 P2 P3  E0 E1 E2 E3 E4 E5  CRC\n"
           "\n"
           "H = 0xEC = 11 1 01 100: marker 1, text bits 01, n = 4\n"
           "L0 = 1000 = 0x03E8: core 0x0F, refinement 0x28; C0 = 0x0F ^ 0x87 = 0x88\n"
           "R0 = -1000 = 0x3C18: core 0xF0, refinement 0x18; C1 = 0xF0 ^ 0x23 = 0xD3"))
S.append(P("The full bit stream of that row, left to right: 10101010 (or 01010101 on the rows with flipped "
           "polarity) 0000 00101110 followed by the 20 bytes above MSB first, 180 bits, 696 pixels between the guards."))

S.append(P("9. Reference implementation", h1))
S.append(P("The PAL-sign repository (github.com/PE5PVB/PAL-sign) contains the executable reference for everything "
           "above:"))
S.append(B("<font face='Courier'>Firmware/tools/pcm_v3_ref.py</font>: encoder, errors-and-erasures decoder, "
           "scrambler, CRC, text channel and a self test; it also writes the tables the firmware uses and a set "
           "of 600 test vectors (<font face='Courier'>PC Software/pcmdecoder/selftest_vectors.txt</font>: 20 row "
           "bytes as hex, then the expected result) plus one text cycle "
           "(<font face='Courier'>selftest_text.txt</font>)."))
S.append(B("<font face='Courier'>Firmware/src/testcards/pcmaudio.cpp</font>: the generator."))
S.append(B("<font face='Courier'>PC Software/pcmdecoder/RowDecoder.cs</font>: a complete decoder from captured "
           "pixels (run-in search, sync, RS with erasures, CRC, text, concealment), C#."))
S.append(P("Measured on hardware with a Blackmagic Intensity Pro capture: 48000 pairs a second, zero corrections "
           "over a cable; the first pixel of the row arrives a handful of pixels (about 6) after the capture's "
           "pixel 0. The capture window sits one line late: capture row 0 is frame row 2 (PAL line 24), capture "
           "row 573 is frame row 575 (line 623, the last row with audio), and the capture's rows 574 and 575 "
           "are lines 311 and 624, which the encoder blanks: they are always empty. Frame rows 0 and 1 fall off "
           "the front of the window, which is why the generator leaves them without pairs."))

S.append(P("10. LQ, Voice and Voice narrow", h1))
S.append(P("The card has four qualities, chosen on the board (the card's option bits 1..0); the row above is "
           "HQ. The other two run at 32 kHz (the board resamples its 48 kHz ADC by an exact 3:2), carry at most "
           "3 pairs a row, keep the same run-in, guard, sync byte, text channel and scrambler, and use a smaller "
           "core codeword, RS(11,7): header, 6 core bytes C0..C5 (L0 R0 L1 R1 L2 R2), 4 parity bytes from the same "
           "generator, two byte errors corrected. Rows carry 0..3 pairs, on average 2.36 (32000 / 13550). A decoder "
           "tells the four apart by the bit period the preamble locks to (3.87, 4.97, 6.44 or 9.16 pixels) before reading "
           "anything; the header's bits 7..6 confirm it."))
S.append(table([
    ["", "LQ", "Voice"],
    ["Samples", "12 bit two's complement (the ADC's 16 bit sample >> 4)", "8 bit ITU-T G.711 A-law of the 16 bit sample, even bits inverted (the usual 0x55 mask)"],
    ["Core byte", "bits 11..4 of the sample", "the A-law byte itself"],
    ["Refinement", "the low 4 bits of each sample: E0 = L0 R0, E1 = L1 R1, E2 = L2 R2 (high nibble first), scrambled with key bytes 8..10, then CRC-8", "none"],
    ["Bits a row", "20 + 88 + 24 + 8 = 140", "20 + 88 = 108"],
    ["Bit cell", "696/140 = 4.971 px; bit k starts at 12 + floor((696 k + 70) / 140)", "696/108 = 6.444 px; bit k starts at 12 + floor((696 k + 54) / 108)"],
    ["Bit rate", "2.72 Mbit/s, fundamental 1.36 MHz", "2.09 Mbit/s, fundamental 1.05 MHz"],
    ["Header bits 7..6", "10", "01"],
    ["Bytes after the sync", "H C0..C5 P0..P3 E0 E1 E2 CRC (15)", "H C0..C5 P0..P3 (11)"],
], [30*mm, 70*mm, 70*mm]))
S.append(Spacer(1, 4))
S.append(P("Reconstruction: LQ s = (core &lt;&lt; 4) | nibble, sign-extend from bit 11, shift left by 4 for 16 bit; a "
           "damaged refinement leaves the row at 8 bits. Voice: A-law decode of the core byte (after unscrambling) gives "
           "the 16 bit sample directly; every bit of the row is inside the RS codeword, so there is no coarse state. "
           "Test vectors: <font face='Courier'>selftest_lq.txt</font> and <font face='Courier'>selftest_voice.txt</font>, "
           "the row bytes as hex and the decoded 16 bit values."))
S.append(P("Voice narrow (option 3) is the fourth quality: mono, 16 kHz (the board averages L and R and resamples "
           "48 kHz by an exact 3:1), 8 bit A-law as in Voice, at most 2 samples a row (on average 1.18, "
           "16000 / 13550) in a RS(7,3) codeword from the same generator: header, 2 A-law bytes C0 C1 (samples 0 "
           "and 1, scrambled with key bytes 0 and 1), 4 parity bytes, two byte errors corrected. The row is "
           "20 + 56 = 76 bits in 696/76 = 9.158 px cells (bit k starts at 12 + floor((696 k + 38) / 76)), 1.47 Mbit/s "
           "with a 0.74 MHz fundamental. Header bits 7..6 are 00, bits 2..0 the sample count 0..2; the text "
           "channel sits in bits 5..3 as before. A decoder plays the one sample on both channels. Test vectors: "
           "<font face='Courier'>selftest_narrow.txt</font>."))

S.append(P("11. Summary of constants", h1))
S.append(table([
    ["Constant", "Value"],
    ["Pixels a bit", "696/180 = 3.867 (13.5 MHz pixel clock, 3.49 Mbit/s); 12 guard pixels each side carry no data"],
    ["Bits a row", "180 = 8 run-in + 4 guard + 8 sync + 104 core codeword + 48 refinement + 8 CRC"],
    ["Sync byte", "0x2E"],
    ["Header", "0xC0 | marker << 5 | text << 3 | n"],
    ["Sample format", "14 bit two's complement, 48 kHz, stereo; up to 4 pairs a row"],
    ["Keystream", "87 23 46 DC B0 DD EE F8 FD C3 5C BF 5C 53 (LFSR 0xB400 taps, seed 0xACE1)"],
    ["RS code", "RS(13,9) over GF(256), poly 0x11D, g(x) = x^4 + 15x^3 + 54x^2 + 120x + 64, roots alpha^0..alpha^3"],
    ["CRC", "CRC-8, poly 0x07, init 0, over E0..E5"],
    ["Text", "10 characters, 6 bit alphabet of 64, 2 bits a row, 30 rows a cycle, marker in header bit 5"],
    ["LQ", "32 kHz, 12 bit, 3 pairs a row, 140 bits in 4.971 px cells (2.72 Mbit/s), RS(11,7), header 0x80 | ..."],
    ["Voice", "32 kHz, 8 bit A-law, 3 pairs a row, 108 bits in 6.444 px cells (2.09 Mbit/s), RS(11,7), header 0x40 | ..."],
    ["Voice narrow", "16 kHz mono, 8 bit A-law, 2 samples a row, 76 bits in 9.158 px cells (1.47 Mbit/s), RS(7,3), header 0x00 | ..."],
], [40*mm, 130*mm]))

S.append(P("12. Change log", h1))
S.append(table([
    ["Version", "Date", "Changes"],
    ["1.0", "30 August 2026", "First issue: HQ (48 kHz, 14 bit), LQ (32 kHz, 12 bit) and Voice (32 kHz, "
        "8 bit A-law), each bit cell 720/N pixels, the text channel, the decoding walkthrough."],
    ["1.1", "30 August 2026", "Fourth quality Voice narrow: 16 kHz mono, 8 bit A-law, 2 samples a row in a "
        "RS(7,3) codeword, 76 bits a row."],
    ["2.0", "30 August 2026", "Guard pixels; not compatible with 1.x. The row no longer fills all 720 active "
        "pixels: the data occupies the middle 696, with 12 black guard pixels at each end of every line, after "
        "field reports that 720x576 capture windows sit shifted by several pixels and clip the row's tail (this "
        "chain's own Blackmagic clips about 7.5 px off the line end). All bit counts and byte layouts are "
        "unchanged; every bit cell is 696/N pixels instead of 720/N, so each mode's instantaneous bit rate "
        "rises by 3.4 percent, and the run-in now starts at pixel 12 instead of 0."],
], [18*mm, 30*mm, 122*mm]))

doc.build(S)
print("wrote", OUT)
