# -*- coding: utf-8 -*-
"""Draw the TVE Carta de Ajuste, the Spanish colour test card.

WHY IT IS DRAWN AND NOT TRACED. The card was designed in 1973 by Finn
Hendil at the Philips TV & Test Equipment laboratory in Amager, the same
team that made the PM5544, and it was generated by a heavily modified
PM5544. No pattern ROM of that machine has survived in
inaxeon/PTV_Preservation, which only holds manuals and schematics for the
PM5544, and hacktv has no Spanish card either. So there is nothing to
demodulate or to dump; it has to be drawn.

The only clean reference in circulation is
commons.wikimedia.org/wiki/File:Recreation_of_TVE_Carta_Ajuste.png, a
16 kB recreation at 768x576. Measured against the published description
of the card it is right about the layout and wrong about the signal:

  gratings      the recreation sweeps continuously from 0.6 to 6.9 MHz.
                6.9 MHz cannot exist in a PAL luminance signal at all.
                The card has five fixed gratings, 0.5, 1.25, 2.25, 4.2
                and 4.8 MHz.
  colour bars   the recreation uses #EAD63D, #00E1C3, #00DB2E, #E707F0,
                #F61F3B and #130FD8. The card carries EBU bars at 75
                percent amplitude and 100 percent saturation.
  2T pulse      missing from the recreation. The black bar at the bottom
                should carry a white vertical line.
  grey scale    six steps of 20 percent. The recreation has these right.

So the GEOMETRY below is measured in that recreation and the LEVELS come
from the description of the card. Every measured number is written down
with what it was measured on.

THE CIRCLE IS ROUND, and that took a second look. Its bounding box in the
recreation is only 486 wide against 512 high, which would make it an
ellipse. It is not: the widest part of the circle is covered by the
colour bars and the blocks below them, so the bounding box only sees the
narrow arcs. Fitting the visible arc at four heights against a vertical
semi axis of 256 gives a horizontal semi axis of 255.2, 255.6, 254.9 and
255.4. It is a circle of 512 by 512 in a 768x576 square pixel frame, and
therefore 480 by 512 in the 720 samples that BT.656 carries.

Usage:
    python tools/make_tve.py [--png out.png] [--check recreation.png]
"""
import argparse
import os
import sys

import numpy as np
from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from convert_rom_pattern import encode_and_write
from make_testcardf import H, W, to_422, fill

FS = 13.5e6

# The recreation is 768 wide with square pixels; we carry 720 samples
# across the same picture width.
SRC_W = 768.0


def qx(x):
    """A horizontal coordinate from the 768 raster into our 720 raster."""
    return x * W / SRC_W


# --- colours ----------------------------------------------------------
#
# The two background colours are published as signal values rather than
# as pixels, which is what we want:
#
#   orange rectangle  luminance 0.66, chroma amplitude 0.369, phase 135
#   light blue circle luminance 0.45, chroma amplitude 0.169, phase -45
#
# Phase is taken from the +U axis, with U = 0.493(B-Y) and V = 0.877(R-Y)
# as in PAL. THAT CONVENTION IS CHECKED AND NOT ASSUMED: reading the
# orange out of the recreation and running it through the same formulas
# gives amplitude 0.371 against the published 0.369 and luminance 0.655
# against 0.66. Any other convention puts the vector somewhere else
# entirely.
def uv_to_rgb(y, amp, phase_deg):
    u = amp * np.cos(np.radians(phase_deg))
    v = amp * np.sin(np.radians(phase_deg))
    b_y = u / 0.493
    r_y = v / 0.877
    r = y + r_y
    b = y + b_y
    g = (y - 0.299 * r - 0.114 * b) / 0.587
    return tuple(float(np.clip(c, 0.0, 1.0) * 255.0) for c in (r, g, b))


ORANGE = uv_to_rgb(0.66, 0.369, 135.0)
BLUE = uv_to_rgb(0.45, 0.169, -45.0)

WHITE = (255.0, 255.0, 255.0)
BLACK = (0.0, 0.0, 0.0)
GREY = (128.0, 128.0, 128.0)      # the grid fields, measured #808080

# EBU bars, 75 percent amplitude and 100 percent saturation: every
# primary is either off or at 75 percent. Yellow, cyan, green, magenta,
# red, blue, in that order across the card.
E = 0.75 * 255.0
BARS = ((E, E, 0.0), (0.0, E, E), (0.0, E, 0.0),
        (E, 0.0, E), (E, 0.0, 0.0), (0.0, 0.0, E))

# Six steps of 20 percent, which is what the recreation has as well
# (0, 51, 102, 153, 204, 255).
STAIRCASE = tuple((round(255.0 * i / 5.0),) * 3 for i in range(6))

# --- geometry, measured in the recreation -----------------------------
# The grid: fields of 38 px separated by white lines of 2 px, so a pitch
# of 40. Measured on row 20, which runs (0,12) (255,13) (128,38) (255,2)
# (128,38) (255,2) ... and on column 60, which runs (255,9) (0,8)
# (128,30) (255,2) (128,38) ...
GRID_STEP = 40.0
GRID_LINE = 2.0
GRID_X0 = 25.0     # first grid field starts here, after the border
GRID_Y0 = 17.0

# The castellation border. Blocks of 40 along each edge, alternating
# black and white; 12 px deep at the left and right, 9 px at the top and
# bottom (measured on column 20 and row 8).
CASTELLATION_W = 12.0
CASTELLATION_H = 9.0

# The orange rectangle, bounding box of #FF9038: x 105..662, y 89..486.
ORANGE_X0, ORANGE_X1 = 105.0, 662.0
ORANGE_Y0, ORANGE_Y1 = 89.0, 486.0

# The circle. Centre from the orange rectangle, which is centred on the
# frame; radius from the arc fit described at the top.
CIR_CX = 383.5
CIR_CY = 287.5
CIR_RX = 255.3
CIR_RY = 256.0

# The white box at the top of the circle: an outline, x 305..464, walls
# 10 px thick. The recreation puts it at rows 30..87, and there its top
# corners hang OUTSIDE the circle: the circle starts at row 31.5 and is
# only 160 wide, which is this box, at row 44.4. Half width 80 needs
# 255.3 * sqrt(1 - (dy/256)^2) = 80, so dy = 243.1 and y = 44.4.
#
# So the box goes down until it is inside, keeping its size: rows 48..105
# leave about 10 samples of blue either side of the top corners.
BOX_X0, BOX_X1 = 305.0, 464.0
BOX_Y0, BOX_Y1 = 48.0, 105.0
BOX_WALL = 10.0

# The colour bar block and the grey staircase under it. The block runs
# x 127..638 and the bar edges sit at 222, 303, 384, 464 and 544, so the
# two outer bars are wider than the four in the middle. Vertical edges
# measured on column 300: 208, 288, 368, 448.
BLOCK_X0, BLOCK_X1 = 127.0, 638.0
BAR_EDGES = (127.0, 222.0, 303.0, 384.0, 464.0, 544.0, 638.0)
BARS_Y0, BARS_Y1 = 208.0, 287.0
STAIRCASE_Y0, STAIRCASE_Y1 = 288.0, 367.0
GRAT_Y0, GRAT_Y1 = 368.0, 447.0

# The five gratings sit in the middle of that band, x 185..581, with the
# rest of the band black on the left and white on the right, carrying on
# the two ends of the staircase above it. Measured on row 400, which runs
# black from 154 to 184, gratings to 581 and white from 582 to 611.
GRAT_X0, GRAT_X1 = 185.0, 581.0
GRAT_MHZ = (0.5e6, 1.25e6, 2.25e6, 4.2e6, 4.8e6)
GRAT_MID = 128.0
GRAT_AMP = 110.0

# The black bar at the bottom, measured x 243..523, y 448..488. The
# recreation leaves it solid; the card carries a 2T pulse in it, so a
# white line goes in the middle.
BAR_X0, BAR_X1 = 243.0, 523.0
BAR_Y0, BAR_Y1 = 448.0, 488.0

# The text areas. NO BLACK BOXES: the text goes straight onto the card,
# so nothing is cut out of the picture for it. textDrawRow() writes solid
# YCbCr including chroma, so white text on the blue circle comes out
# white and not pale blue.
#
# Both areas are kept inside the circle, with room to spare. The circle
# half width is 255.3 * sqrt(1 - (dy/256)^2), so at the top area (dy 176
# to 112) that is 184 to 229 and at the bottom area (dy 199 to 237) it is
# 161 to 98. The areas below fit inside the narrowest row of each.
#
# Top area: the blue between the white box, which ends at row 87, and the
# colour bars, which start at row 208. Row 112..172 is where TVE put its
# wordmark; this is placed a little higher instead, so it no longer
# matches the recreation -- kept in step with tve.cpp's own TXT1_Y0/Y1
# for the circle-margin check() below, not measured from the source.
TEXT1_X0, TEXT1_X1 = 230.0, 537.0
TEXT1_Y0, TEXT1_Y1 = 104.0, 164.0
# Bottom area: the bottom of the circle, below the black bar.
TEXT2_X0, TEXT2_X1 = 305.0, 462.0
TEXT2_Y0, TEXT2_Y1 = 490.0, 524.0
# The date and the clock, left and right on the grid below the orange,
# where the broadcast card had them. Eight rows higher than the card has
# them, because rows 492 to 528 is 85 to 92 percent down the picture and
# that is where a set with any overscan starts losing things.
DATE_X0, DATE_X1 = 62.0, 232.0
TIME_X0, TIME_X1 = 536.0, 706.0
INS_Y0, INS_Y1 = 484.0, 520.0


def rectangle(b, x0, x1, y0, y1, colour):
    """Fill in 768 space; the horizontal edges are converted on the way."""
    fill(b, int(round(qx(x0))), int(round(qx(x1 + 1))) - 1, int(y0), int(y1), colour)


def draw_background(b):
    """The grid of grey fields with white lines, and the castellations."""
    b[:, :] = np.array(WHITE)

    # Grid fields. The pitch is square on screen: 40 lines vertically and
    # the same physical width horizontally, which is 37.5 samples here.
    y = GRID_Y0
    while y < H:
        x = GRID_X0
        while x < SRC_W:
            rectangle(b, x, min(x + GRID_STEP - GRID_LINE - 1, SRC_W - 1),
                      y, min(y + GRID_STEP - GRID_LINE - 1, H - 1), GREY)
            x += GRID_STEP
        y += GRID_STEP

    # Castellations: blocks of 40 along the four edges, alternating black
    # and white, so the outer edge of the picture is easy to find.
    n = 0
    x = 0.0
    while x < SRC_W:
        if n % 2 == 0:
            rectangle(b, x, min(x + GRID_STEP - 1, SRC_W - 1), 0, CASTELLATION_H - 1, BLACK)
            rectangle(b, x, min(x + GRID_STEP - 1, SRC_W - 1), H - CASTELLATION_H, H - 1, BLACK)
        x += GRID_STEP
        n += 1
    n = 0
    y = 0.0
    while y < H:
        if n % 2 == 0:
            rectangle(b, 0, CASTELLATION_W - 1, y, min(y + GRID_STEP - 1, H - 1), BLACK)
            rectangle(b, SRC_W - CASTELLATION_W, SRC_W - 1, y, min(y + GRID_STEP - 1, H - 1), BLACK)
        y += GRID_STEP
        n += 1


def circle_mask():
    """Which samples lie inside the circle.

    Built in our own raster so the circle is round on a 4:3 screen: 512
    lines high and 480 samples wide.
    """
    yy, xx = np.mgrid[0:H, 0:W]
    return (((xx - qx(CIR_CX)) / qx(CIR_RX)) ** 2 +
            ((yy - CIR_CY) / CIR_RY) ** 2) <= 1.0


def draw_circle(b, inside):
    rectangle(b, ORANGE_X0, ORANGE_X1, ORANGE_Y0, ORANGE_Y1, ORANGE)
    b[inside] = np.array(BLUE)


def draw_white_box(b):
    rectangle(b, BOX_X0, BOX_X1, BOX_Y0, BOX_Y1, WHITE)
    rectangle(b, BOX_X0 + BOX_WALL, BOX_X1 - BOX_WALL,
              BOX_Y0 + BOX_WALL, BOX_Y1 - BOX_WALL, BLUE)


def draw_bars(b):
    for i, colour in enumerate(BARS):
        rectangle(b, BAR_EDGES[i], BAR_EDGES[i + 1] - 1, BARS_Y0, BARS_Y1, colour)
    # The staircase uses the same six divisions as the bars above it, so
    # every step lines up with the colour over it.
    for i, colour in enumerate(STAIRCASE):
        rectangle(b, BAR_EDGES[i], BAR_EDGES[i + 1] - 1, STAIRCASE_Y0, STAIRCASE_Y1, colour)


def draw_gratings(b):
    """Five sine gratings side by side, at the published frequencies.

    A sine and not a square wave: a square wave at 4.8 MHz would put its
    third harmonic at 14.4 MHz, above the sampling rate, and what came
    out would be an alias and not a resolution test.
    """
    rectangle(b, BLOCK_X0, GRAT_X0 - 1, GRAT_Y0, GRAT_Y1, BLACK)
    rectangle(b, GRAT_X1 + 1, BLOCK_X1, GRAT_Y0, GRAT_Y1, WHITE)

    x0 = int(round(qx(GRAT_X0)))
    x1 = int(round(qx(GRAT_X1 + 1))) - 1
    width = (x1 - x0 + 1) / float(len(GRAT_MHZ))
    n = np.arange(W)
    for i, hz in enumerate(GRAT_MHZ):
        a = int(round(x0 + i * width))
        c = int(round(x0 + (i + 1) * width)) - 1
        v = np.clip(GRAT_MID + GRAT_AMP * np.sin(2 * np.pi * hz * n / FS), 0, 255)
        b[int(GRAT_Y0):int(GRAT_Y1) + 1, a:c + 1] = v[None, a:c + 1, None]


def draw_2t_bar(b):
    """The black bar with a 2T pulse in it.

    2T at 5 MHz system bandwidth is a sin squared pulse of 2/(2*5 MHz) =
    200 ns half amplitude duration, which is 2.7 samples at 13.5 MHz. It
    is drawn as the pulse itself and not as a hard white line, because a
    hard line is not a 2T pulse and would ring on anything that filters
    it.
    """
    rectangle(b, BAR_X0, BAR_X1, BAR_Y0, BAR_Y1, BLACK)
    hd = 2.0 / (2.0 * 5.0e6)                 # 200 ns
    mid = qx((BAR_X0 + BAR_X1) / 2.0)
    t = (np.arange(W) - mid) / FS
    pulse = np.where(np.abs(t) <= hd, np.cos(np.pi * t / (2.0 * hd)) ** 2, 0.0)
    y0, y1 = int(BAR_Y0), int(BAR_Y1)
    b[y0:y1 + 1, :, :] = np.maximum(b[y0:y1 + 1, :, :], (255.0 * pulse)[None, :, None])


def draw_card():
    """The measurement blocks are CLIPPED TO THE CIRCLE.

    They are drawn as full rectangles first, because their edges and
    widths are measured that way, and then everything outside the circle
    is put back to what the background had there. Without that the block
    sticks out of the circle wherever the circle is narrower than its
    widest row, which is everywhere except the middle two lines.
    """
    b = np.zeros((H, W, 3), np.float64)
    inside = circle_mask()
    draw_background(b)
    draw_circle(b, inside)
    draw_white_box(b)

    under = b.copy()
    draw_bars(b)
    draw_gratings(b)
    draw_2t_bar(b)
    b[~inside] = under[~inside]
    return b


def measure_grating(row, x0, x1):
    """Frequency of a grating by FFT, so the answer does not depend on
    where the zero crossings happen to fall."""
    seg = row[x0:x1 + 1] - row[x0:x1 + 1].mean()
    if len(seg) < 8:
        return 0.0
    sp = np.abs(np.fft.rfft(seg * np.hanning(len(seg))))
    k = int(np.argmax(sp[1:])) + 1
    return k * FS / len(seg)


def check(card):
    print("  levels:")
    print("    orange  R%3.0f G%3.0f B%3.0f  (from Y 0.66, chroma 0.369 at 135 deg)" % ORANGE)
    print("    blue    R%3.0f G%3.0f B%3.0f  (from Y 0.45, chroma 0.169 at -45 deg)" % BLUE)
    print("  gratings measured back out of the drawing:")
    x0 = int(round(qx(GRAT_X0)))
    x1 = int(round(qx(GRAT_X1 + 1))) - 1
    width = (x1 - x0 + 1) / float(len(GRAT_MHZ))
    row = card[(int(GRAT_Y0) + int(GRAT_Y1)) // 2, :, 0]
    for i, hz in enumerate(GRAT_MHZ):
        a = int(round(x0 + i * width)) + 2
        c = int(round(x0 + (i + 1) * width)) - 3
        got = measure_grating(row, a, c)
        print("    wanted %.2f MHz, measured %.2f MHz (%+.1f percent)"
              % (hz / 1e6, got / 1e6, 100.0 * (got - hz) / hz))
    # The circle has to be round on screen: equal physical radius.
    print("  circle: %.1f samples by %.1f lines; round on a 4:3 screen needs %.1f by %.1f"
          % (2 * qx(CIR_RX), 2 * CIR_RY, 2 * CIR_RY * W / SRC_W, 2 * CIR_RY))
    print("  text areas in our 720 raster, copy these into tve.cpp:")
    for name, x0, x1, y0, y1 in (("text 1", TEXT1_X0, TEXT1_X1, TEXT1_Y0, TEXT1_Y1),
                                 ("text 2", TEXT2_X0, TEXT2_X1, TEXT2_Y0, TEXT2_Y1),
                                 ("date  ", DATE_X0, DATE_X1, INS_Y0, INS_Y1),
                                 ("clock ", TIME_X0, TIME_X1, INS_Y0, INS_Y1)):
        print("    %s x %3d..%3d  y %3d..%3d"
              % (name, int(round(qx(x0))), int(round(qx(x1 + 1))) - 1, int(y0), int(y1)))


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--png", help="write the drawing as a PNG as well")
    a = p.parse_args()

    print("TVE Carta de Ajuste")
    card = draw_card()
    check(card)

    if a.png:
        Image.fromarray(np.clip(card, 0, 255).astype(np.uint8)).save(a.png)
        print("  %s written" % a.png)

    cfg = {"title": "TVE Carta de Ajuste",
           "file": "-",
           "note": "drawn; layout from the recreation, levels and "
                          "gratings from the published description"}
    encode_and_write("tve", cfg, [to_422(card)], 0)


if __name__ == "__main__":
    sys.exit(main())
