# -*- coding: utf-8 -*-
"""The small font for the ST7789 status display.

    python tools/make_display_font.py --nimbus ~/Downloads/NimbusSanL-Bol.otf

WHY A THIRD FONT. The two fonts in font_data.h are drawn for the test
card and are 30 and 24 rows high. The display is 76 pixels high, so only
two lines of those would fit and there is more than that to show. At 16
rows there is room for four lines.

WHY NOT THE SAME TABLE. font_data.h keeps every character as
uint32_t[FONT_MAX_ROWS] with FONT_MAX_ROWS at 44, because the tallest
font in it needs that. A 16 row font in that table would carry 28 empty
rows per character. Its own table costs a quarter of the flash and the
firmware needs the two for completely different things: one goes into a
4:2:2 picture row, this one into RGB565 pixels.

THE SHAPES come from the same Nimbus Sans Bold as the PM8546 font, so
the display and the picture are in one typeface.

THE POINT SIZE IS SEARCHED FOR and not given. What a font does with a
point size depends on the font, and what this file needs is a height in
PIXELS. So it renders at one size after another and keeps the one whose
ink band is exactly the number of rows asked for.
"""
import argparse
import io
import os
import sys

import numpy as np

from make_fonts import CHARS, digit_width, from_otf, normalise

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "display_font.h")

# Space between two characters, in pixels. One column is enough at this
# size; two makes a line of twenty characters run past the text area.
GAP = 1

# The space has no ink, so it has no width of its own to measure.
SPACE_W = 4

# The test card fonts are upper case only, which is right for a PM5544.
# The display shows the names of the cards as the firmware spells them,
# "EBU bars and red" and so on, so it needs lower case as well. The
# descenders of g, j, p, q and y are what makes the ink band taller than
# the capitals, and that is the height DISPFONT_ROWS counts.
DISPLAY_CHARS = CHARS + "abcdefghijklmnopqrstuvwxyz"


def at_rows(path, rows):
    """The glyphs at exactly `rows` pixels of ink height.

    Returns (glyphs, points). Raises if no point size gives that height,
    which is possible: the height does not go up one pixel at a time.
    """
    seen = {}
    for points in range(6, 40):
        g = from_otf(path, points, DISPLAY_CHARS)
        h = g[0][1].shape[0]
        seen[h] = points
        if h == rows:
            return normalise(g, SPACE_W), points
    raise SystemExit("no point size gives %d rows; the sizes on offer are %s"
                     % (rows, ", ".join(str(h) for h in sorted(seen))))


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--nimbus", required=True, help="NimbusSanL-Bol.otf")
    p.add_argument("--rows", type=int, default=16, help="ink height in pixels (default 16)")
    a = p.parse_args()

    glyphs, points = at_rows(a.nimbus, a.rows)
    widest = max(w for c, m, w in glyphs)
    digit = digit_width(glyphs)
    if widest > 32:
        raise SystemExit("the widest character is %d columns and a row is one uint32_t" % widest)

    nl = chr(10)
    with io.open(OUT, "w", encoding="utf-8", newline=nl) as fh:
        w = fh.write
        w("// GENERATED by tools/make_display_font.py -- do not edit by hand." + nl)
        w("//" + nl)
        w("// Nimbus Sans Bold at %d points, which comes out at %d rows of ink." % (points, a.rows)
          + nl)
        w("// The same typeface as the PM8546 font in font_data.h, so the" + nl)
        w("// display and the picture do not disagree about the shapes." + nl)
        w("//" + nl)
        w("// Bit 31 of each row is the leftmost column. The rows are the ink" + nl)
        w("// only: every character sits on the same baseline and is cropped" + nl)
        w("// to its own width, so the table carries no empty columns." + nl)
        w("#pragma once" + nl + nl)
        w("#include <stdint.h>" + nl + nl)
        w("static const int DISPFONT_ROWS = %d;" % a.rows + nl)
        w("// Between two characters. Digits all get DISPFONT_DIGIT_W so that a" + nl)
        w("// running clock does not jump when a 1 comes round." + nl)
        w("static const int DISPFONT_GAP = %d;" % GAP + nl)
        w("static const int DISPFONT_DIGIT_W = %d;" % digit + nl)
        w("static const int DISPFONT_MAX_W = %d;" % widest + nl + nl)
        w("struct DispGlyph {" + nl)
        w("  uint8_t ch;                    // the character itself, 1 = O with a slash" + nl)
        w("  uint8_t w;                     // ink columns" + nl)
        w("  uint32_t r[DISPFONT_ROWS];     // bit 31 = leftmost column" + nl)
        w("};" + nl + nl)
        w("static const DispGlyph DISPLAY_FONT[] = {" + nl)
        for c, m, width in glyphs:
            # The space carries a width but no ink at all, so its raster
            # is one empty column while its width is SPACE_W. Walk the
            # raster, not the width.
            words = []
            for r in range(m.shape[0]):
                v = 0
                for x in range(min(width, m.shape[1])):
                    if m[r, x]:
                        v |= 1 << (31 - x)
                words.append("0x%08X" % v)
            label = ("%3d" % ord(c)) if (ord(c) < 32 or ord(c) > 126) else ("'%s'" % c)
            if c == "'":
                label = "'" + chr(92) + "''"
            w("    {%s, %2d, {%s}}," % (label, width, ", ".join(words)) + nl)
        w("};" + nl + nl)
        w("static const int DISPLAY_FONT_COUNT = %d;" % len(glyphs) + nl)

    print("%s written" % os.path.normpath(OUT))
    print("  %d characters, %d rows at %d points" % (len(glyphs), a.rows, points))
    print("  widest %d columns, digits %d, gap %d" % (widest, digit, GAP))
    print("  %d bytes of flash" % (len(glyphs) * (2 + 2 + 4 * a.rows)))


if __name__ == "__main__":
    sys.exit(main())
