"""
Turns a TFT_eSPI style background into the byte order this panel wants.

    python tools/make_display_bg.py tft_bg_radiaal_180x76.h src/display_bg.h

The input is a uint16_t array of RGB565 in the ordinary order, which is
what the usual generators produce. Everything kept as a colour in
display.cpp is stored the other way round, high byte first, so that a
transfer is a straight copy of memory to the SPI and costs no work per
pixel. This swaps the whole picture once, here, instead of 13680 times
per redraw on the board.

IT HAS TO BE EXACTLY THE TEXT AREA: 180 by 76, the part of the panel to
the right of the rule. The tool refuses anything else, because a
background that is one pixel out would shift every row against the one
above it and that is hard to see and easy to miss.
"""

import argparse
import io
import os
import re
import sys

NL = chr(10)

WIDTH, HEIGHT = 180, 76


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("input", help="the .h with the uint16_t array")
    p.add_argument("output", help="where to write the header")
    a = p.parse_args()

    text = io.open(a.input, encoding="utf-8", errors="replace").read()
    body = text[text.index("{"):]
    values = [int(v, 16) for v in re.findall(r"0x([0-9A-Fa-f]{4})", body)]
    if len(values) != WIDTH * HEIGHT:
        raise SystemExit("expected %d pixels for %dx%d, found %d"
                         % (WIDTH * HEIGHT, WIDTH, HEIGHT, len(values)))

    swapped = [((v >> 8) | (v << 8)) & 0xFFFF for v in values]

    out = []
    out.append("// GENERATED by tools/make_display_bg.py -- do not edit by hand.")
    out.append("//")
    out.append("// The background of the text area, %d by %d, RGB565 in the order the"
               % (WIDTH, HEIGHT))
    out.append("// panel wants: high byte first. Row major and exactly as wide as the")
    out.append("// text area, so the rows of one line of text are one run of memory and")
    out.append("// a redraw is a single memcpy.")
    out.append("//")
    out.append("// Source: %s" % os.path.basename(a.input))
    out.append("#pragma once")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("static const int DISPLAY_BG_W = %d;" % WIDTH)
    out.append("static const int DISPLAY_BG_H = %d;" % HEIGHT)
    out.append("")
    out.append("static const uint16_t DISPLAY_BG[DISPLAY_BG_W * DISPLAY_BG_H] = {")
    for y in range(HEIGHT):
        row = swapped[y * WIDTH:(y + 1) * WIDTH]
        for i in range(0, WIDTH, 12):
            out.append("    " + " ".join("0x%04X," % v for v in row[i:i + 12]))
    out.append("};")

    io.open(a.output, "w", encoding="ascii", newline=NL).write(NL.join(out) + NL)

    distinct = len(set(swapped))
    print("%s: %dx%d, %d bytes of flash, %d distinct colours"
          % (os.path.basename(a.output), WIDTH, HEIGHT, WIDTH * HEIGHT * 2, distinct))
    return 0


if __name__ == "__main__":
    sys.exit(main())
