#!/usr/bin/env python3
"""Generates the polyphase interpolation filters for the firmware's
sample-rate converter (src/asrc.cpp), 48 kHz in: src/asrc_taps.h for
44.1 kHz out (the Sony/EIAJ card) and src/asrc_taps_32.h for 32 kHz
out (the Ham PCM LQ card), the same design with the cut-off moved.

A Kaiser-windowed sinc, PHASES x TAPS coefficients, Q15. The prototype
is a low-pass at the input rate with its cut-off just under half the
OUTPUT rate, so it both interpolates and anti-aliases for the
down-conversion. Each phase row is normalised to unity DC gain.

Linear interpolation was rejected on purpose: at a ratio near 1 the
interpolation phase drifts slowly, and at phase 0.5 linear
interpolation attenuates 20 kHz at 44.1 kHz by cos(pi * 20/44.1) =
0.146, minus 17 dB, periodically. See notes/sony-pcm.md.

Run from Firmware/: python tools/make_asrc.py   (writes both)
"""
import math

PHASES = 32
FIN = 48000.0
# (output rate, cut-off, taps a phase, Kaiser beta, file, macro suffix).
# The 32 kHz set is shorter: the ASRC has to fit the 64 us row budget
# of the Ham PCM LQ card, and 32 taps (~15 us a row) starved the
# picture. 20 taps, cut-off 14.5 kHz, beta 4 measured on the prototype:
# -0.3 dB at 12 kHz, -4 dB at 14 kHz, -16 dB at 16 kHz (the alias
# edge), -50 dB at 18 kHz; 16 taps were either 3 dB down at 12 kHz or
# only 10 dB down at 16 kHz. The response is printed for the record.
SETS = [
    (44100.0, 19800.0, 32, 8.0, "src/asrc_taps.h", ""),
    (32000.0, 14500.0, 20, 4.0, "src/asrc_taps_32.h", "_32"),
    (16000.0, 7500.0, 32, 4.0, "src/asrc_taps_16.h", "_16"),   # Voice narrow, mono 16 kHz: 1.2 samples a row leave room for 32 taps
]


def kaiser(n, N, beta):
    # I0 via series, plenty for these sizes.
    def i0(x):
        s, t, k = 1.0, 1.0, 1
        while t > 1e-12 * s:
            t *= (x / (2 * k)) ** 2
            s += t
            k += 1
        return s
    r = 2.0 * n / (N - 1) - 1.0
    return i0(beta * math.sqrt(max(0.0, 1 - r * r))) / i0(beta)


def main():
    for fout, cutoff, taps, beta, path, suffix in SETS:
        make(fout, cutoff, taps, beta, path, suffix)


def response_db(rows, f_hz):
    """Gain of the prototype (all phases interleaved) at f_hz, in dB."""
    proto = []
    for k in range(len(rows[0])):
        for p in range(PHASES):
            proto.append(rows[p][k] / 32767.0)
    w = 2 * math.pi * f_hz / (FIN * PHASES)
    re = sum(c * math.cos(w * n) for n, c in enumerate(proto))
    im = sum(c * math.sin(w * n) for n, c in enumerate(proto))
    return 20 * math.log10(max(1e-12, math.hypot(re, im) / PHASES))


def make(FOUT, CUTOFF_HZ, TAPS, KAISER_BETA, path, suffix):
    N = PHASES * TAPS
    fc = CUTOFF_HZ / (FIN * PHASES)      # cycles per upsampled sample
    centre = (N - 1) / 2.0
    proto = []
    for n in range(N):
        x = n - centre
        s = 2 * fc if x == 0 else math.sin(2 * math.pi * fc * x) / (math.pi * x)
        proto.append(s * kaiser(n, N, KAISER_BETA))
    rows = []
    for p in range(PHASES):
        row = [proto[k * PHASES + p] for k in range(TAPS)]
        g = sum(row)
        row = [int(round(c / g * 32767.0)) for c in row]
        rows.append(row)
    guard = "ASRC_TAPS" + suffix.upper() + "_H"
    with open(path, "w", newline="\n") as f:
        f.write("// Generated by tools/make_asrc.py; do not edit by hand.\n")
        f.write("// Polyphase interpolation filter for src/asrc.cpp: Kaiser-windowed\n")
        f.write(f"// sinc, cut-off {CUTOFF_HZ:.0f} Hz at {FIN:.0f} Hz in for {FOUT:.0f} Hz out, beta {KAISER_BETA}, Q15,\n")
        f.write("// each phase normalised to unity DC gain.\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n#include <stdint.h>\n\n")
        if suffix == "":
            f.write(f"static const int ASRC_PHASES = {PHASES};\n")
        f.write(f"static const int ASRC_TAPS{suffix} = {TAPS};\n\n")
        f.write(f"static const int16_t ASRC_COEF{suffix}[{PHASES}][{TAPS}] = {{\n")
        for row in rows:
            f.write("  {" + ", ".join(f"{c}" for c in row) + "},\n")
        f.write(f"}};\n\n#endif  // {guard}\n")
    worst = max(sum(abs(c) for c in r) for r in rows)
    # asrc.cpp accumulates in int32: sum|h| * 32767 must stay under 2^31.
    assert worst * 32767 < 2**31, "taps too large for a 32 bit accumulator"
    print(f"wrote {path}, max sum|h| per phase = {worst} "
          f"(x 32767 = {worst * 32767}, under 2^31 = {2**31}: int32 accumulate is safe)")
    edge = FOUT / 2
    print(f"  response: {CUTOFF_HZ * 0.85:.0f} Hz {response_db(rows, CUTOFF_HZ * 0.85):.1f} dB, "
          f"{edge:.0f} Hz {response_db(rows, edge):.1f} dB, {edge * 1.15:.0f} Hz {response_db(rows, edge * 1.15):.1f} dB, "
          f"{edge * 1.3:.0f} Hz {response_db(rows, edge * 1.3):.1f} dB")


if __name__ == "__main__":
    main()
