#!/usr/bin/env python3
"""Renders the contest counter digits from Titillium Web.

The counter on the contest page used to be limited to the raster fonts
of the cards; an outline font drawn at the FINAL size gives clean curves
where a raster font, however well its edges are followed, keeps hard
corners. Only the ten digits are taken over: everything else on the page
stays in the card font.

THE SIZE IS NOT A CHOICE HERE. The digits are rendered at exactly the
ink height the raster font reached in the number box: PM5544 digits are
30 font rows of ink, the box is 176 rows (NR_Y0..NR_Y1 in contest.cpp)
and the fit rule caps the scale at 5, so the counter stood 150 rows
tall and that is the height rendered here. The font size that yields a
150 row digit is found by search, because a TrueType point size names
the em and not the digit height.

The face is TitilliumWeb-Bold.ttf next to this script (SIL OFL 1.1,
from the Google Fonts repository): the counter carries the bold weight,
the two text lines around it stay regular (make_contest_font.py). The
output is one header of RUNS, not of bare coverage bytes: see
contest_rle.py for the form and for why a byte per pixel drained the
ring buffer to black.

Writes src/testcards/contest_digits.h. Run from the tools directory.
"""

from PIL import Image, ImageDraw, ImageFont

from contest_rle import emit_rle

TARGET_H = 150            # the ink height the raster font reached, see above
DIGITS = "0123456789"
FONT_FILE = "TitilliumWeb-Bold.ttf"
OUT = "../src/testcards/contest_digits.h"

CANVAS = (600, 600)
ORIGIN = (50, 400)        # baseline anchor, comfortably inside the canvas


def union_bbox(size):
    """The joint ink box of all ten digits at this point size."""
    font = ImageFont.truetype(FONT_FILE, size)
    x0 = y0 = 10**6
    x1 = y1 = -(10**6)
    for d in DIGITS:
        img = Image.new("L", CANVAS, 0)
        ImageDraw.Draw(img).text(ORIGIN, d, font=font, fill=255, anchor="ls")
        b = img.getbbox()
        x0, y0 = min(x0, b[0]), min(y0, b[1])
        x1, y1 = max(x1, b[2]), max(y1, b[3])
    return (x0, y0, x1, y1)


def find_size():
    """The point size whose digits stand TARGET_H pixels tall.

    Walked rather than solved: the mapping from point size to rendered
    ink height quantises to whole pixels, so the answer is the largest
    size that does not overshoot."""
    size = TARGET_H            # a starting point below the answer
    while True:
        b = union_bbox(size + 1)
        if b[3] - b[1] > TARGET_H:
            break
        size += 1
    return size


def main():
    size = find_size()
    font = ImageFont.truetype(FONT_FILE, size)
    ub = union_bbox(size)
    height = ub[3] - ub[1]
    print(f"point size {size}, digit band {height} rows (target {TARGET_H})")

    pieces = []
    for d in DIGITS:
        img = Image.new("L", CANVAS, 0)
        ImageDraw.Draw(img).text(ORIGIN, d, font=font, fill=255, anchor="ls")
        b = img.getbbox()
        # Own width, but the SHARED vertical band: a 1 without an
        # under- or overshoot still has to stand on the same line as
        # the rounded 0 beside it.
        crop = img.crop((b[0], ub[1], b[2], ub[3]))
        pieces.append((d, crop))

    cell = max(p.width for _, p in pieces)
    with open(OUT, "w", newline="\n") as f:
        f.write("// Generated by tools/make_contest_digits.py -- do not edit.\n")
        f.write("// The ten counter digits from Titillium Web (SIL OFL 1.1) as\n")
        f.write("// runs, rendered at the final size so the firmware never scales\n")
        f.write("// them. See tools/contest_rle.py for the run form and for why\n")
        f.write("// it is not a byte of coverage per pixel.\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write(f"static const int CONTEST_DIGIT_H = {height};\n")
        f.write(f"static const int CONTEST_DIGIT_CELL = {cell};\n\n")
        total = 0
        for d, p in pieces:
            total += emit_rle(f, f"CONTEST_DIGIT_{d}", p.tobytes(), p.width, p.height)
        f.write("\nstruct ContestDigit {\n")
        f.write("  uint8_t w;\n")
        f.write("  const uint16_t *off;   // CONTEST_DIGIT_H + 1 row offsets\n")
        f.write("  const uint8_t *rle;    // the tokens, see tools/contest_rle.py\n")
        f.write("};\n\n")
        f.write("static const ContestDigit CONTEST_DIGITS[10] = {\n")
        for d, p in pieces:
            f.write(f"    {{{p.width}, CONTEST_DIGIT_{d}_O, CONTEST_DIGIT_{d}_R}},\n")
        f.write("};\n")
    print(f"cell {cell} wide, {total} bytes of tokens -> {OUT}")


if __name__ == "__main__":
    main()
