#!/usr/bin/env python3
"""Builds src/ticker_font.h: five fixed sizes, extra small through
extra large, for each of the ticker band's two run-glyph faces, every
one drawn at its own true size, no scaling anywhere.

NO RUNTIME SCALING: each size is a complete, independent bake, drawn
exactly like a single fixed size would be, so every one costs at render
time exactly what a single proven size costs, whichever is picked. A
shared master shrunk at render time was tried and reverted: walking a
source row at master resolution costs more per row than the budget
allows, whatever size is actually asked for, because the source never
gets smaller than the master. The only price of baking five is Flash,
paid once per size kept.

60 keeps the ORIGINAL symbol names (TICKER_FONT, TICKER_FONT_SQUARE):
that is the size every card had before the other four existed, so code
that only ever knew one size still finds it under the name it always
had. The other four are suffixed _XSMALL, _SMALL, _LARGE, _XLARGE.

One header, two faces times five sizes, because the ticker offers a
choice of face and every size of both needs the same ring margins
(ticker.cpp's EDGE_TOTAL static_assert leans on that): Inter (built by
make_contest_font.py's own build_into()) and Doto (build_into() in
make_picdream_font.py). Each of those two scripts also builds a second,
face-specific header of its own (contest_font.h, picdream_font.h); their
build() is split into build()+build_into() so this script can pull just
the ticker face out of each without mixing those other cards in.

Run from the tools directory; both face files (Inter-Regular.ttf,
Doto.ttf) sit next to the two scripts imported below.
"""

from make_contest_font import build_into as build_inter
from make_picdream_font import build_into as build_square

OUT = "../src/ticker_font.h"

# (cap target, symbol suffix)
SIZES = [
    (35, "_XSMALL"),
    (45, "_SMALL"),
    (60, ""),
    (70, "_LARGE"),
    (90, "_XLARGE"),
]


def main():
    with open(OUT, "w", newline="\n") as f:
        f.write("// Generated by tools/make_ticker_font.py -- do not edit.\n")
        f.write("// The ticker band's two faces, as runs, each in five fixed\n")
        f.write("// sizes (35/45/60/70/90 row capitals) so the firmware never\n")
        f.write("// scales them at render time: Inter (SIL OFL 1.1) and Doto\n")
        f.write("// (SIL OFL 1.1, https://github.com/oliverlalan/Doto). See\n")
        f.write("// tools/contest_rle.py for the run form and the two generators\n")
        f.write("// for what yoff, lsb and adv mean.\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write('#include "runglyph.h"\n\n')
        for target, suffix in SIZES:
            build_inter(f, target, f"TICKER_FONT{suffix}", "TickerGlyph", rings=True)
            f.write("\n")
        for target, suffix in SIZES:
            build_square(f, target, f"TICKER_FONT_SQUARE{suffix}", "TickerGlyph", rings=True)
            f.write("\n")
    print(f"  -> {OUT}")


if __name__ == "__main__":
    main()
