"""Regenerates src/PortraitGeometry.g.cs from the firmware's own oval
tables (Firmware/src/testcards/testcardf_photo.h and testcardw_photo.h).

    python make_portrait_geometry.py

Why this exists: the firmware substitutes an uploaded photo into the
BBC Test Card F/W photo window by copying it into exactly the same
per-row (x0, length) spans as the built-in photo (see
Firmware/src/portrait.h). The PC tool's centering dialog needs those
same spans, to show the oval and to pack an upload into the shape the
firmware expects; hand-copying 302 and 310 numbers into C# is exactly
the kind of drift this project avoids elsewhere (see ALGO_VERSION in
compare.py). Re-run this whenever the firmware's own tables change.
"""

import os
import re

ROOT = os.path.dirname(os.path.abspath(__file__))
FW = os.path.join(ROOT, "..", "..", "Firmware", "src", "testcards")
OUT = os.path.join(ROOT, "src", "PortraitGeometry.g.cs")


def read_table(path, name):
    txt = open(path).read()
    y0 = int(re.search(r"_PHOTO_Y0 = (\d+)", txt).group(1))
    rows = int(re.search(r"_PHOTO_ROWS = (\d+)", txt).group(1))
    x0 = [int(v) for v in re.search(name + r"_photo_x0\[[^\]]*\]\s*=\s*\{([^}]*)\}",
                                     txt, re.S).group(1).split(",") if v.strip()]
    length = [int(v) for v in re.search(name + r"_photo_len\[[^\]]*\]\s*=\s*\{([^}]*)\}",
                                         txt, re.S).group(1).split(",") if v.strip()]
    assert len(x0) == rows and len(length) == rows, "%s: table length != PHOTO_ROWS" % name
    return y0, rows, x0, length


def emit(w, cname, y0, rows, x0, length):
    w.write("    public static readonly PortraitOval %s = new(\n" % cname)
    w.write("        y0: %d,\n" % y0)
    w.write("        x0: new ushort[] {%s},\n" % ", ".join(str(v) for v in x0))
    w.write("        length: new ushort[] {%s});\n\n" % ", ".join(str(v) for v in length))


def main():
    f = read_table(os.path.join(FW, "testcardf_photo.h"), "testcardf")
    w = read_table(os.path.join(FW, "testcardw_photo.h"), "testcardw")
    with open(OUT, "w") as out:
        out.write("// GENERATED by make_portrait_geometry.py -- do not edit by hand.\n")
        out.write("//\n")
        out.write("// The oval photo window of BBC Test Card F and W, one (x0, length)\n")
        out.write("// span per row, straight from the firmware's own testcardf_photo.h /\n")
        out.write("// testcardw_photo.h. See portrait.h in the firmware for what this feeds.\n")
        out.write("namespace PalSign;\n\n")
        out.write("public readonly struct PortraitOval\n{\n")
        out.write("    public readonly int Y0;\n")
        out.write("    public readonly ushort[] X0;\n")
        out.write("    public readonly ushort[] Length;\n")
        out.write("    public int Rows => X0.Length;\n\n")
        out.write("    public PortraitOval(int y0, ushort[] x0, ushort[] length)\n")
        out.write("    {\n        Y0 = y0;\n        X0 = x0;\n        Length = length;\n    }\n}\n\n")
        out.write("public static class PortraitGeometry\n{\n")
        emit(out, "TestCardF", *f)
        emit(out, "TestCardW", *w)
        out.write("}\n")
    print("wrote %s (F: %d rows, W: %d rows)" % (OUT, f[1], w[1]))


if __name__ == "__main__":
    main()
